// Muppet RaceMania
// #ID = 13910

// $0B0230: 01 = im Turnier (De)
function ImTurnierDe() => byte(0x0B0230)

// $0B0240: 01 = nell torneo (It)
function NellTorneoIt() => byte(0x0B0240)

// $0B037C: 01 = dans le tournoi (Fr)
function DansLeTournoiFr() => byte(0x0B037C)

// $0B03E0: 01 = en torneo (Es)
function EnTorneoEs() => byte(0x0B03E0)

// $0B04EC: 02 = Punkte des Turniers summiert (De)
function PunkteDesTurniersSummiertDe() => byte(0x0B04EC)

// $0B04FC: 02 = punti del torneo aggiunti (It)
function PuntiDelTorneoAggiuntiIt() => byte(0x0B04FC)

// $0B0634: 02 = Points du tournoi ajoutés (Fr)
function PointsDuTournoiAjoutésFr() => byte(0x0B0634)

// $0B069C: 02 = puntos de torneo sumados (Es)
function PuntosDeTorneoSumadosEs() => byte(0x0B069C)

// $0B07E4: 01 = In tournament (US)
function InTournamentUs() => byte(0x0B07E4)

// $0B08C8: Musiklautstärke (De)
function MusiklautstärkeDe() => byte(0x0B08C8)

// $0B08C9: Tonlautstärke (De)
function TonlautstärkeDe() => byte(0x0B08C9)

// $0B08CA: Aktuelle Strecke (De)
function AktuelleStreckeDe() => byte(0x0B08CA)

// $0B08D0: Aktuelle Set von Strecken (De)
function AktuelleSetVonStreckenDe() => byte(0x0B08D0)

// $0B08D8: Volume della musica (It)
function VolumeDellaMusicaIt() => byte(0x0B08D8)

// $0B08D9: Volume del suono (It)
function VolumeDelSuonoIt() => byte(0x0B08D9)

// $0B08DA: Percorso corrente (It)
function PercorsoCorrenteIt() => byte(0x0B08DA)

// $0B08E0: Set di percorsi corrente (It)
function SetDiPercorsiCorrenteIt() => byte(0x0B08E0)

// $0B0A12: Parcours courante (Fr)
function ParcoursCouranteFr() => byte(0x0B0A12)

// $0B0A18: Set de parcourses courante (Fr)
function SetDeParcoursesCouranteFr() => byte(0x0B0A18)

// $0B0A64: 02 = added currently completed race's points (US)
function AddedCurrentlyCompletedRaceSPointsUs() => byte(0x0B0A64)

// $0B0A78: Volumen de música (Es)
function VolumenDeMúsicaEs() => byte(0x0B0A78)

// $0B0A79: Volumen de sonido (Es)
function VolumenDeSonidoEs() => byte(0x0B0A79)

// $0B0A7A: Pista actual (Es)
function PistaActualEs() => byte(0x0B0A7A)

// $0B0A80: Set de pistas actual (Es)
function SetDePistasActualEs() => byte(0x0B0A80)

// $0B0E30: Music volume (US)
function MusicVolumeUs() => byte(0x0B0E30)

// $0B0E31: Sound volume (US)
function SoundVolumeUs() => byte(0x0B0E31)

// $0B0E32: Current course (US)
function CurrentCourseUs() => byte(0x0B0E32)

// $0B0E38: Current course set (US)
function CurrentCourseSetUs() => byte(0x0B0E38)

// $0B0F8C: 01 = in tournament (EU)
function InTournamentEu() => byte(0x0B0F8C)

// $0B1244: 02 = added currently completed race's points (EU)
function AddedCurrentlyCompletedRaceSPointsEu() => byte(0x0B1244)

// $0B1620: Music volume (EU)
function MusicVolumeEu() => byte(0x0B1620)

// $0B1621: Sound volume (EU)
function SoundVolumeEu() => byte(0x0B1621)

// $0B1622: Current course (EU)
function CurrentCourseEu() => byte(0x0B1622)

// $0B1628: Current course set (EU)
function CurrentCourseSetEu() => byte(0x0B1628)

// $0C18C6: Nummer von fertige Rennen im Turnier (De)
function NummerVonFertigeRennenImTurnierDe() => byte(0x0C18C6)

// $0C18D6: Numero di gare finite nel torneo (it)
function NumeroDiGareFiniteNelTorneoIt() => byte(0x0C18D6)

// $0C18D8: Punktzahl des Spielers im Turnier (De)
function PunktzahlDesSpielersImTurnierDe() => byte(0x0C18D8)

// $0C18D9: Punktzahl von Com 1 im Turnier (De)
function PunktzahlVonCom1ImTurnierDe() => byte(0x0C18D9)

// $0C18DA: Punktzahl von Com 2 in Turnier (De)
function PunktzahlVonCom2InTurnierDe() => byte(0x0C18DA)

// $0C18DB: Punktzahl von Com 3 inm Turnier (De)
function PunktzahlVonCom3InmTurnierDe() => byte(0x0C18DB)

// $0C18DC: Punktzahl von Com 4 im Turnier (De)
function PunktzahlVonCom4ImTurnierDe() => byte(0x0C18DC)

// $0C18DD: Punktzahl von Com 5 im Turnier (De)
function PunktzahlVonCom5ImTurnierDe() => byte(0x0C18DD)

// $0C18E8: Punteggio del giocatore nel torneo (It)
function PunteggioDelGiocatoreNelTorneoIt() => byte(0x0C18E8)

// $0C18E9: Punteggio del com 1 nel torneo (It)
function PunteggioDelCom1NelTorneoIt() => byte(0x0C18E9)

// $0C18EA: Punteggio del com 2 nel torneo (It)
function PunteggioDelCom2NelTorneoIt() => byte(0x0C18EA)

// $0C18EB: Punteggio del com 3 nell torneo (It)
function PunteggioDelCom3NellTorneoIt() => byte(0x0C18EB)

// $0C18EC: Punteggio del com 4 nell torneo (It)
function PunteggioDelCom4NellTorneoIt() => byte(0x0C18EC)

// $0C18ED: Punteggio del com 5 nell torneo (It)
function PunteggioDelCom5NellTorneoIt() => byte(0x0C18ED)

// $0C1A0E: Nombre de courses finis dans le tournoi (Fr)
function NombreDeCoursesFinisDansLeTournoiFr() => byte(0x0C1A0E)

// $0C1A20: Ponctuation du joueur dans le tournoi (Fr)
function PonctuationDuJoueurDansLeTournoiFr() => byte(0x0C1A20)

// $0C1A21: Ponctuation du Com 1 dans le tournoi (Fr)
function PonctuationDuCom1DansLeTournoiFr() => byte(0x0C1A21)

// $0C1A22: Ponctuation du Com 2 dans le tournoi (Fr)
function PonctuationDuCom2DansLeTournoiFr() => byte(0x0C1A22)

// $0C1A23: Ponctuation du Com 3 dans le tournoi (Fr)
function PonctuationDuCom3DansLeTournoiFr() => byte(0x0C1A23)

// $0C1A24: Ponctuation du Com 4 dans le tournoi (Fr)
function PonctuationDuCom4DansLeTournoiFr() => byte(0x0C1A24)

// $0C1A25: Ponctuation du Com 5 dans le tournoi (Fr)
function PonctuationDuCom5DansLeTournoiFr() => byte(0x0C1A25)

// $0C1A76: Número de carreras acabadas en torneo (Es)
function NúmeroDeCarrerasAcabadasEnTorneoEs() => byte(0x0C1A76)

// $0C1A88: Puntuación del jugador en torneo (Es)
function PuntuaciónDelJugadorEnTorneoEs() => byte(0x0C1A88)

// $0C1A89: Puntuación de Com 1 en torneo (Es)
function PuntuaciónDeCom1EnTorneoEs() => byte(0x0C1A89)

// $0C1A8A: Puntuación de Com 2 en torneo (Es)
function PuntuaciónDeCom2EnTorneoEs() => byte(0x0C1A8A)

// $0C1A8B: Puntuación de Com 3 en torneo (Es)
function PuntuaciónDeCom3EnTorneoEs() => byte(0x0C1A8B)

// $0C1A8C: Puntuación de Com 4 en torneo (Es)
function PuntuaciónDeCom4EnTorneoEs() => byte(0x0C1A8C)

// $0C1A8D: Puntuación de Com 5 en torneo (Es)
function PuntuaciónDeCom5EnTorneoEs() => byte(0x0C1A8D)

// $0C1DEE: Number of races finished in tournament (US)
function NumberOfRacesFinishedInTournamentUs() => byte(0x0C1DEE)

// $0C1E00: Player's tournament score (US)
function PlayerSTournamentScoreUs() => byte(0x0C1E00)

// $0C1E01: Com 1's tournament score (US)
function Com1STournamentScoreUs() => byte(0x0C1E01)

// $0C1E02: Com 2's tournament score (US)
function Com2STournamentScoreUs() => byte(0x0C1E02)

// $0C1E03: Com 3's tournament score (US)
function Com3STournamentScoreUs() => byte(0x0C1E03)

// $0C1E04: Com 4's tournament score (US)
function Com4STournamentScoreUs() => byte(0x0C1E04)

// $0C1E05: Com 5's tournament score (US)
function Com5STournamentScoreUs() => byte(0x0C1E05)

// $0C1E48: Current tournament (US)
function CurrentTournamentUs() => byte(0x0C1E48)

// $0C269E: Number of races finished in tournament (EU)
function NumberOfRacesFinishedInTournamentEu() => byte(0x0C269E)

// $0C26B0: Player's tournament score (EU)
function PlayerSTournamentScoreEu() => byte(0x0C26B0)

// $0C26B1: Com 1's tournament score (EU)
function Com1STournamentScoreEu() => byte(0x0C26B1)

// $0C26B2: Com 2's tournament score (EU)
function Com2STournamentScoreEu() => byte(0x0C26B2)

// $0C26B3: Com 3's tournament score (EU)
function Com3STournamentScoreEu() => byte(0x0C26B3)

// $0C26B4: Com 4's tournament score (EU)
function Com4STournamentScoreEu() => byte(0x0C26B4)

// $0C26B5: Com 5's tournament score (EU)
function Com5STournamentScoreEu() => byte(0x0C26B5)

// $0C3010: Platz im Rennen (De)
function PlatzImRennenDe() => byte(0x0C3010)

// $0C3020: Posizione del giocatore (It)
function PosizioneDelGiocatoreIt() => byte(0x0C3020)

// $0C302A: Boost des Spielers (De)
function BoostDesSpielersDe() => word(0x0C302A)

// $0C303A: Turbo del giocatore (It)
function TurboDelGiocatoreIt() => word(0x0C303A)

// $0C3158: Position du joueur (Fr)
function PositionDuJoueurFr() => byte(0x0C3158)

// $0C3172: Turbo du joueur (Fr)
function TurboDuJoueurFr() => word(0x0C3172)

// $0C31C0: Posición del jugador (Es)
function PosiciónDelJugadorEs() => byte(0x0C31C0)

// $0C31DA: Turbo del jugador (Es)
function TurboDelJugadorEs() => word(0x0C31DA)

// $0C3532: Player's boost (max = 1a4) (US)
function PlayerSBoostMax() => word(0x0C3532)

// $0C3572: Player's race position (US)
function PlayerSRacePositionUs() => byte(0x0C3572)

// $0C3E10: Player's race position (EU)
function PlayerSRacePositionEu() => byte(0x0C3E10)

// $0C3E2A: Current boost (EU)
function CurrentBoostEu() => word(0x0C3E2A)

// $0E0194: Swamp best lap character (US)
function SwampBestLapCharacterUs() => byte(0x0E0194)

// $0E0195: Swamp best lap vehicle (US)
function SwampBestLapVehicleUs() => byte(0x0E0195)

// $0E0197: Swamp objective flags (US)
//          Bit 0 = boss
function SwampObjectiveFlagsUs() => byte(0x0E0197)

// $0E019E: Ghost town objective flags (US)
function GhostTownObjectiveFlagsUs() => bit1(0x0E019E)
function GhostTownObjectiveFlagsUs() => bit2(0x0E019E)
function GhostTownObjectiveFlagsUs() => bit3(0x0E019E)
function GhostTownObjectiveFlagsUs() => bit4(0x0E019E)
function GhostTownObjectiveFlagsUs() => bit5(0x0E019E)
function GhostTownObjectiveFlagsUs() => bit7(0x0E019E)

// $0E01A6: Canyon objective flags (US)
function CanyonObjectiveFlagsUs() => bit1(0x0E01A6)
function CanyonObjectiveFlagsUs() => bit2(0x0E01A6)
function CanyonObjectiveFlagsUs() => bit3(0x0E01A6)
function CanyonObjectiveFlagsUs() => bit4(0x0E01A6)
function CanyonObjectiveFlagsUs() => bit5(0x0E01A6)
function CanyonObjectiveFlagsUs() => bit7(0x0E01A6)

// $0E01AE: Funfair objective flags (US)
function FunfairObjectiveFlagsUs() => bit1(0x0E01AE)
function FunfairObjectiveFlagsUs() => bit2(0x0E01AE)
function FunfairObjectiveFlagsUs() => bit3(0x0E01AE)
function FunfairObjectiveFlagsUs() => bit4(0x0E01AE)
function FunfairObjectiveFlagsUs() => bit5(0x0E01AE)
function FunfairObjectiveFlagsUs() => bit6(0x0E01AE)
function FunfairObjectiveFlagsUs() => bit7(0x0E01AE)

// $0E01B6: Happiness Hotel objective flags (US)
function HappinessHotelObjectiveFlagsUs() => bit1(0x0E01B6)
function HappinessHotelObjectiveFlagsUs() => bit2(0x0E01B6)
function HappinessHotelObjectiveFlagsUs() => bit3(0x0E01B6)
function HappinessHotelObjectiveFlagsUs() => bit4(0x0E01B6)
function HappinessHotelObjectiveFlagsUs() => bit5(0x0E01B6)
function HappinessHotelObjectiveFlagsUs() => bit6(0x0E01B6)
function HappinessHotelObjectiveFlagsUs() => bit7(0x0E01B6)

// $0E01BE: Mallory Gallery objective flags (US)
function MalloryGalleryObjectiveFlagsUs() => bit1(0x0E01BE)
function MalloryGalleryObjectiveFlagsUs() => bit2(0x0E01BE)
function MalloryGalleryObjectiveFlagsUs() => bit3(0x0E01BE)
function MalloryGalleryObjectiveFlagsUs() => bit4(0x0E01BE)
function MalloryGalleryObjectiveFlagsUs() => bit5(0x0E01BE)
function MalloryGalleryObjectiveFlagsUs() => bit6(0x0E01BE)
function MalloryGalleryObjectiveFlagsUs() => bit7(0x0E01BE)

// $0E01C6: Trafalgar Square objective flags (US)
function TrafalgarSquareObjectiveFlagsUs() => bit1(0x0E01C6)
function TrafalgarSquareObjectiveFlagsUs() => bit2(0x0E01C6)
function TrafalgarSquareObjectiveFlagsUs() => bit3(0x0E01C6)
function TrafalgarSquareObjectiveFlagsUs() => bit4(0x0E01C6)
function TrafalgarSquareObjectiveFlagsUs() => bit5(0x0E01C6)
function TrafalgarSquareObjectiveFlagsUs() => bit7(0x0E01C6)

// $0E01CE: Restaurant objective flags (US)
function RestaurantObjectiveFlagsUs() => bit1(0x0E01CE)
function RestaurantObjectiveFlagsUs() => bit2(0x0E01CE)
function RestaurantObjectiveFlagsUs() => bit3(0x0E01CE)
function RestaurantObjectiveFlagsUs() => bit4(0x0E01CE)
function RestaurantObjectiveFlagsUs() => bit5(0x0E01CE)
function RestaurantObjectiveFlagsUs() => bit6(0x0E01CE)
function RestaurantObjectiveFlagsUs() => bit7(0x0E01CE)

// $0E01D6: Central Park objective flags (US)
function CentralParkObjectiveFlagsUs() => bit1(0x0E01D6)
function CentralParkObjectiveFlagsUs() => bit2(0x0E01D6)
function CentralParkObjectiveFlagsUs() => bit3(0x0E01D6)
function CentralParkObjectiveFlagsUs() => bit4(0x0E01D6)
function CentralParkObjectiveFlagsUs() => bit5(0x0E01D6)
function CentralParkObjectiveFlagsUs() => bit7(0x0E01D6)

// $0E01DE: New York City objective flags (US)
function NewYorkCityObjectiveFlagsUs() => bit1(0x0E01DE)
function NewYorkCityObjectiveFlagsUs() => bit2(0x0E01DE)
function NewYorkCityObjectiveFlagsUs() => bit3(0x0E01DE)
function NewYorkCityObjectiveFlagsUs() => bit4(0x0E01DE)
function NewYorkCityObjectiveFlagsUs() => bit5(0x0E01DE)
function NewYorkCityObjectiveFlagsUs() => bit6(0x0E01DE)
function NewYorkCityObjectiveFlagsUs() => bit7(0x0E01DE)

// $0E01E6: Theatre objective flags (US)
function TheatreObjectiveFlagsUs() => bit1(0x0E01E6)
function TheatreObjectiveFlagsUs() => bit2(0x0E01E6)
function TheatreObjectiveFlagsUs() => bit3(0x0E01E6)
function TheatreObjectiveFlagsUs() => bit4(0x0E01E6)
function TheatreObjectiveFlagsUs() => bit5(0x0E01E6)
function TheatreObjectiveFlagsUs() => bit7(0x0E01E6)

// $0E01EE: Diner objective flags (US)
function DinerObjectiveFlagsUs() => bit1(0x0E01EE)
function DinerObjectiveFlagsUs() => bit2(0x0E01EE)
function DinerObjectiveFlagsUs() => bit3(0x0E01EE)
function DinerObjectiveFlagsUs() => bit4(0x0E01EE)
function DinerObjectiveFlagsUs() => bit5(0x0E01EE)
function DinerObjectiveFlagsUs() => bit6(0x0E01EE)
function DinerObjectiveFlagsUs() => bit7(0x0E01EE)

// $0E01F6: Old London Town objective flags (US)
function OldLondonTownObjectiveFlagsUs() => bit1(0x0E01F6)
function OldLondonTownObjectiveFlagsUs() => bit2(0x0E01F6)
function OldLondonTownObjectiveFlagsUs() => bit3(0x0E01F6)
function OldLondonTownObjectiveFlagsUs() => bit4(0x0E01F6)
function OldLondonTownObjectiveFlagsUs() => bit5(0x0E01F6)
function OldLondonTownObjectiveFlagsUs() => bit6(0x0E01F6)
function OldLondonTownObjectiveFlagsUs() => bit7(0x0E01F6)

// $0E01FE: Graveyard objective flags (US)
function GraveyardObjectiveFlagsUs() => bit1(0x0E01FE)
function GraveyardObjectiveFlagsUs() => bit2(0x0E01FE)
function GraveyardObjectiveFlagsUs() => bit3(0x0E01FE)
function GraveyardObjectiveFlagsUs() => bit4(0x0E01FE)
function GraveyardObjectiveFlagsUs() => bit5(0x0E01FE)
function GraveyardObjectiveFlagsUs() => bit6(0x0E01FE)
function GraveyardObjectiveFlagsUs() => bit7(0x0E01FE)

// $0E0206: Chamber objective flags (US)
function ChamberObjectiveFlagsUs() => bit1(0x0E0206)
function ChamberObjectiveFlagsUs() => bit2(0x0E0206)
function ChamberObjectiveFlagsUs() => bit3(0x0E0206)
function ChamberObjectiveFlagsUs() => bit4(0x0E0206)
function ChamberObjectiveFlagsUs() => bit5(0x0E0206)
function ChamberObjectiveFlagsUs() => bit7(0x0E0206)

// $0E020E: Rooftops objective flags (US)
function RooftopsObjectiveFlagsUs() => bit1(0x0E020E)
function RooftopsObjectiveFlagsUs() => bit2(0x0E020E)
function RooftopsObjectiveFlagsUs() => bit3(0x0E020E)
function RooftopsObjectiveFlagsUs() => bit4(0x0E020E)
function RooftopsObjectiveFlagsUs() => bit5(0x0E020E)
function RooftopsObjectiveFlagsUs() => bit6(0x0E020E)
function RooftopsObjectiveFlagsUs() => bit7(0x0E020E)

// $0E0216: Dock objective flags (US)
function DockObjectiveFlagsUs() => bit1(0x0E0216)
function DockObjectiveFlagsUs() => bit2(0x0E0216)
function DockObjectiveFlagsUs() => bit3(0x0E0216)
function DockObjectiveFlagsUs() => bit4(0x0E0216)
function DockObjectiveFlagsUs() => bit5(0x0E0216)
function DockObjectiveFlagsUs() => bit6(0x0E0216)
function DockObjectiveFlagsUs() => bit7(0x0E0216)

// $0E021E: Treasure Island objective flags (US)
function TreasureIslandObjectiveFlagsUs() => bit1(0x0E021E)
function TreasureIslandObjectiveFlagsUs() => bit2(0x0E021E)
function TreasureIslandObjectiveFlagsUs() => bit3(0x0E021E)
function TreasureIslandObjectiveFlagsUs() => bit4(0x0E021E)
function TreasureIslandObjectiveFlagsUs() => bit5(0x0E021E)
function TreasureIslandObjectiveFlagsUs() => bit6(0x0E021E)
function TreasureIslandObjectiveFlagsUs() => bit7(0x0E021E)

// $0E0226: Lagoon objective flags (US)
function LagoonObjectiveFlagsUs() => bit1(0x0E0226)
function LagoonObjectiveFlagsUs() => bit2(0x0E0226)
function LagoonObjectiveFlagsUs() => bit3(0x0E0226)
function LagoonObjectiveFlagsUs() => bit4(0x0E0226)
function LagoonObjectiveFlagsUs() => bit5(0x0E0226)
function LagoonObjectiveFlagsUs() => bit7(0x0E0226)

// $0E022E: Mountain objective flags (US)
function MountainObjectiveFlagsUs() => bit1(0x0E022E)
function MountainObjectiveFlagsUs() => bit2(0x0E022E)
function MountainObjectiveFlagsUs() => bit3(0x0E022E)
function MountainObjectiveFlagsUs() => bit4(0x0E022E)
function MountainObjectiveFlagsUs() => bit5(0x0E022E)
function MountainObjectiveFlagsUs() => bit6(0x0E022E)
function MountainObjectiveFlagsUs() => bit7(0x0E022E)

// $0E0236: Secret Base objective flags (US)
function SecretBaseObjectiveFlagsUs() => bit1(0x0E0236)
function SecretBaseObjectiveFlagsUs() => bit2(0x0E0236)
function SecretBaseObjectiveFlagsUs() => bit3(0x0E0236)
function SecretBaseObjectiveFlagsUs() => bit4(0x0E0236)
function SecretBaseObjectiveFlagsUs() => bit5(0x0E0236)
function SecretBaseObjectiveFlagsUs() => bit6(0x0E0236)
function SecretBaseObjectiveFlagsUs() => bit7(0x0E0236)

// $0E023E: Cape Doom objective flags (US)
function CapeDoomObjectiveFlagsUs() => bit1(0x0E023E)
function CapeDoomObjectiveFlagsUs() => bit2(0x0E023E)
function CapeDoomObjectiveFlagsUs() => bit3(0x0E023E)
function CapeDoomObjectiveFlagsUs() => bit4(0x0E023E)
function CapeDoomObjectiveFlagsUs() => bit5(0x0E023E)
function CapeDoomObjectiveFlagsUs() => bit6(0x0E023E)
function CapeDoomObjectiveFlagsUs() => bit7(0x0E023E)

// $0E0246: Laboratory objective flags (US)
function LaboratoryObjectiveFlagsUs() => bit1(0x0E0246)
function LaboratoryObjectiveFlagsUs() => bit2(0x0E0246)
function LaboratoryObjectiveFlagsUs() => bit3(0x0E0246)
function LaboratoryObjectiveFlagsUs() => bit4(0x0E0246)
function LaboratoryObjectiveFlagsUs() => bit5(0x0E0246)
function LaboratoryObjectiveFlagsUs() => bit7(0x0E0246)

// $0E024E: Muppet Labs objective flags (US)
function MuppetLabsObjectiveFlagsUs() => bit1(0x0E024E)
function MuppetLabsObjectiveFlagsUs() => bit2(0x0E024E)
function MuppetLabsObjectiveFlagsUs() => bit3(0x0E024E)
function MuppetLabsObjectiveFlagsUs() => bit4(0x0E024E)
function MuppetLabsObjectiveFlagsUs() => bit5(0x0E024E)
function MuppetLabsObjectiveFlagsUs() => bit6(0x0E024E)
function MuppetLabsObjectiveFlagsUs() => bit7(0x0E024E)

// $0E0256: Studio objective flags (US)
function StudioObjectiveFlagsUs() => bit1(0x0E0256)
function StudioObjectiveFlagsUs() => bit2(0x0E0256)
function StudioObjectiveFlagsUs() => bit3(0x0E0256)
function StudioObjectiveFlagsUs() => bit4(0x0E0256)
function StudioObjectiveFlagsUs() => bit7(0x0E0256)

// $0E025E: Arches objective flags (US)
function ArchesObjectiveFlagsUs() => bit1(0x0E025E)
function ArchesObjectiveFlagsUs() => bit2(0x0E025E)
function ArchesObjectiveFlagsUs() => bit3(0x0E025E)
function ArchesObjectiveFlagsUs() => bit4(0x0E025E)
function ArchesObjectiveFlagsUs() => bit7(0x0E025E)

// $0E0266: Fraggle Rock objective flags (US)
function FraggleRockObjectiveFlagsUs() => bit1(0x0E0266)
function FraggleRockObjectiveFlagsUs() => bit2(0x0E0266)
function FraggleRockObjectiveFlagsUs() => bit3(0x0E0266)
function FraggleRockObjectiveFlagsUs() => bit4(0x0E0266)
function FraggleRockObjectiveFlagsUs() => bit7(0x0E0266)

// $0E026E: Disco objective flags (US)
function DiscoObjectiveFlagsUs() => bit1(0x0E026E)
function DiscoObjectiveFlagsUs() => bit2(0x0E026E)
function DiscoObjectiveFlagsUs() => bit3(0x0E026E)
function DiscoObjectiveFlagsUs() => bit4(0x0E026E)
function DiscoObjectiveFlagsUs() => bit7(0x0E026E)

// $0E04DE: Flags von Ziele von Sumpf (De)
function FlagsVonZieleVonSumpfDe() => bit0(0x0E04DE)
function FlagsVonZieleVonSumpfDe() => bit1(0x0E04DE)
function FlagsVonZieleVonSumpfDe() => bit2(0x0E04DE)
function FlagsVonZieleVonSumpfDe() => bit3(0x0E04DE)
function FlagsVonZieleVonSumpfDe() => bit4(0x0E04DE)
function FlagsVonZieleVonSumpfDe() => bit5(0x0E04DE)
function FlagsVonZieleVonSumpfDe() => bit6(0x0E04DE)
function FlagsVonZieleVonSumpfDe() => bit7(0x0E04DE)

// $0E0626: Flags d'objectifs de Marais (Fr)
function FlagsDObjectifsDeMaraisFr() => bit0(0x0E0626)
function FlagsDObjectifsDeMaraisFr() => bit1(0x0E0626)
function FlagsDObjectifsDeMaraisFr() => bit2(0x0E0626)
function FlagsDObjectifsDeMaraisFr() => bit3(0x0E0626)
function FlagsDObjectifsDeMaraisFr() => bit4(0x0E0626)
function FlagsDObjectifsDeMaraisFr() => bit5(0x0E0626)
function FlagsDObjectifsDeMaraisFr() => bit6(0x0E0626)
function FlagsDObjectifsDeMaraisFr() => bit7(0x0E0626)

// $0E068E: Flags de objetivos de ciénaga (Es)
function FlagsDeObjetivosDeCiénagaEs() => bit0(0x0E068E)
function FlagsDeObjetivosDeCiénagaEs() => bit1(0x0E068E)
function FlagsDeObjetivosDeCiénagaEs() => bit2(0x0E068E)
function FlagsDeObjetivosDeCiénagaEs() => bit3(0x0E068E)
function FlagsDeObjetivosDeCiénagaEs() => bit4(0x0E068E)
function FlagsDeObjetivosDeCiénagaEs() => bit5(0x0E068E)
function FlagsDeObjetivosDeCiénagaEs() => bit6(0x0E068E)
function FlagsDeObjetivosDeCiénagaEs() => bit7(0x0E068E)

// $0E1D86: Swamp objective flags (EU)
function SwampObjectiveFlagsEu() => bit0(0x0E1D86)
function SwampObjectiveFlagsEu() => bit1(0x0E1D86)
function SwampObjectiveFlagsEu() => bit2(0x0E1D86)
function SwampObjectiveFlagsEu() => bit3(0x0E1D86)
function SwampObjectiveFlagsEu() => bit4(0x0E1D86)
function SwampObjectiveFlagsEu() => bit5(0x0E1D86)
function SwampObjectiveFlagsEu() => bit6(0x0E1D86)
function SwampObjectiveFlagsEu() => bit7(0x0E1D86)

achievement(
    title = "100% Swamp", points = 10,
    description = "Complete all the objectives in Swamp",
    id = 129003, badge = "141600", published = "2020-10-13 4:31:43 PM", modified = "2022-07-27 8:58:06 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 0 && CurrentCourseUs() == 0 && (prev(bit1(0x0E0196)) + prev(bit2(0x0E0196)) +
                 prev(bit3(0x0E0196)) + prev(bit4(0x0E0196)) + prev(bit5(0x0E0196)) + prev(bit6(0x0E0196)) +
                 prev(bit7(0x0E0196))) == 6 && measured((bit1(0x0E0196) + bit2(0x0E0196) + bit3(0x0E0196) +
                 bit4(0x0E0196) + bit5(0x0E0196) + bit6(0x0E0196) + bit7(0x0E0196)) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 0 && CurrentCourseEu() == 0 && (prev(SwampObjectiveFlagsEu()) + prev(SwampObjectiveFlagsEu()) +
                 prev(SwampObjectiveFlagsEu()) + prev(SwampObjectiveFlagsEu()) + prev(SwampObjectiveFlagsEu()) + prev(SwampObjectiveFlagsEu()) +
                 prev(SwampObjectiveFlagsEu())) == 6 && measured((SwampObjectiveFlagsEu() + SwampObjectiveFlagsEu() + SwampObjectiveFlagsEu() +
                 SwampObjectiveFlagsEu() + SwampObjectiveFlagsEu() + SwampObjectiveFlagsEu() + SwampObjectiveFlagsEu()) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 0 && AktuelleStreckeDe() == 0 && (prev(FlagsVonZieleVonSumpfDe()) + prev(FlagsVonZieleVonSumpfDe()) +
                 prev(FlagsVonZieleVonSumpfDe()) + prev(FlagsVonZieleVonSumpfDe()) + prev(FlagsVonZieleVonSumpfDe()) + prev(FlagsVonZieleVonSumpfDe()) +
                 prev(FlagsVonZieleVonSumpfDe())) == 6 && measured((FlagsVonZieleVonSumpfDe() + FlagsVonZieleVonSumpfDe() + FlagsVonZieleVonSumpfDe() +
                 FlagsVonZieleVonSumpfDe() + FlagsVonZieleVonSumpfDe() + FlagsVonZieleVonSumpfDe() + FlagsVonZieleVonSumpfDe()) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 0 && PercorsoCorrenteIt() == 0 && (prev(bit1(0x0E04EE)) + prev(bit2(0x0E04EE)) +
                 prev(bit3(0x0E04EE)) + prev(bit4(0x0E04EE)) + prev(bit5(0x0E04EE)) + prev(bit6(0x0E04EE)) +
                 prev(bit7(0x0E04EE))) == 6 && measured((bit1(0x0E04EE) + bit2(0x0E04EE) + bit3(0x0E04EE) +
                 bit4(0x0E04EE) + bit5(0x0E04EE) + bit6(0x0E04EE) + bit7(0x0E04EE)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 0 && ParcoursCouranteFr() == 0 && (prev(FlagsDObjectifsDeMaraisFr()) + prev(FlagsDObjectifsDeMaraisFr()) +
                 prev(FlagsDObjectifsDeMaraisFr()) + prev(FlagsDObjectifsDeMaraisFr()) + prev(FlagsDObjectifsDeMaraisFr()) + prev(FlagsDObjectifsDeMaraisFr()) +
                 prev(FlagsDObjectifsDeMaraisFr())) == 6 && measured((FlagsDObjectifsDeMaraisFr() + FlagsDObjectifsDeMaraisFr() + FlagsDObjectifsDeMaraisFr() +
                 FlagsDObjectifsDeMaraisFr() + FlagsDObjectifsDeMaraisFr() + FlagsDObjectifsDeMaraisFr() + FlagsDObjectifsDeMaraisFr()) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 0 && PistaActualEs() == 0 && (prev(FlagsDeObjetivosDeCiénagaEs()) + prev(FlagsDeObjetivosDeCiénagaEs()) +
                 prev(FlagsDeObjetivosDeCiénagaEs()) + prev(FlagsDeObjetivosDeCiénagaEs()) + prev(FlagsDeObjetivosDeCiénagaEs()) + prev(FlagsDeObjetivosDeCiénagaEs()) +
                 prev(FlagsDeObjetivosDeCiénagaEs())) == 6 && measured((FlagsDeObjetivosDeCiénagaEs() + FlagsDeObjetivosDeCiénagaEs() + FlagsDeObjetivosDeCiénagaEs() +
                 FlagsDeObjetivosDeCiénagaEs() + FlagsDeObjetivosDeCiénagaEs() + FlagsDeObjetivosDeCiénagaEs() + FlagsDeObjetivosDeCiénagaEs()) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Ghost Town", points = 10,
    description = "Complete all the objectives in Ghost Town",
    id = 129004, badge = "141601", published = "2020-10-13 4:31:47 PM", modified = "2022-07-27 8:58:41 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 0 && CurrentCourseUs() == 1 && (prev(GhostTownObjectiveFlagsUs()) + prev(GhostTownObjectiveFlagsUs()) +
                 prev(GhostTownObjectiveFlagsUs()) + prev(GhostTownObjectiveFlagsUs()) + prev(GhostTownObjectiveFlagsUs()) + prev(GhostTownObjectiveFlagsUs())) == 5 && 
                measured((GhostTownObjectiveFlagsUs() + GhostTownObjectiveFlagsUs() + GhostTownObjectiveFlagsUs() + GhostTownObjectiveFlagsUs() + GhostTownObjectiveFlagsUs() +
                 GhostTownObjectiveFlagsUs()) == 6, when=MusicVolumeUs() <= 15 && SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 &&
                 PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 || CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 ||
                 CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 && SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 &&
                 SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 0 && CurrentCourseEu() == 1 && (prev(bit1(0x0E1D8E)) + prev(bit2(0x0E1D8E)) +
                 prev(bit3(0x0E1D8E)) + prev(bit4(0x0E1D8E)) + prev(bit5(0x0E1D8E)) + prev(bit7(0x0E1D8E))) == 5 && 
                measured((bit1(0x0E1D8E) + bit2(0x0E1D8E) + bit3(0x0E1D8E) + bit4(0x0E1D8E) + bit5(0x0E1D8E) +
                 bit7(0x0E1D8E)) == 6, when=MusicVolumeEu() <= 15 && SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 &&
                 PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 || CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 ||
                 CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 && byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 &&
                 byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 0 && AktuelleStreckeDe() == 1 && (prev(bit1(0x0E04E6)) + prev(bit2(0x0E04E6)) +
                 prev(bit3(0x0E04E6)) + prev(bit4(0x0E04E6)) + prev(bit5(0x0E04E6)) + prev(bit7(0x0E04E6))) == 5 && 
                measured((bit1(0x0E04E6) + bit2(0x0E04E6) + bit3(0x0E04E6) + bit4(0x0E04E6) + bit5(0x0E04E6) +
                 bit7(0x0E04E6)) == 6, when=MusiklautstärkeDe() <= 15 && TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 &&
                 PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 && byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 &&
                 byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 0 && PercorsoCorrenteIt() == 1 && (prev(bit1(0x0E04F6)) + prev(bit2(0x0E04F6)) +
                 prev(bit3(0x0E04F6)) + prev(bit4(0x0E04F6)) + prev(bit5(0x0E04F6)) + prev(bit7(0x0E04F6))) == 5 && 
                measured((bit1(0x0E04F6) + bit2(0x0E04F6) + bit3(0x0E04F6) + bit4(0x0E04F6) + bit5(0x0E04F6) +
                 bit7(0x0E04F6)) == 6, when=VolumeDellaMusicaIt() <= 15 && VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 &&
                 PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 && byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 &&
                 byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 0 && ParcoursCouranteFr() == 1 && (prev(bit1(0x0E062E)) + prev(bit2(0x0E062E)) +
                 prev(bit3(0x0E062E)) + prev(bit4(0x0E062E)) + prev(bit5(0x0E062E)) + prev(bit7(0x0E062E))) == 5 && 
                measured((bit1(0x0E062E) + bit2(0x0E062E) + bit3(0x0E062E) + bit4(0x0E062E) + bit5(0x0E062E) +
                 bit7(0x0E062E)) == 6, when=byte(0x0BA010) <= 15 && byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 &&
                 PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 && byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 &&
                 byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 0 && PistaActualEs() == 1 && (prev(bit1(0x0E0696)) + prev(bit2(0x0E0696)) +
                 prev(bit3(0x0E0696)) + prev(bit4(0x0E0696)) + prev(bit5(0x0E0696)) + prev(bit7(0x0E0696))) == 5 && 
                measured((bit1(0x0E0696) + bit2(0x0E0696) + bit3(0x0E0696) + bit4(0x0E0696) + bit5(0x0E0696) +
                 bit7(0x0E0696)) == 6, when=VolumenDeMúsicaEs() <= 15 && VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 &&
                 PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 && byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 &&
                 byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Canyon", points = 10,
    description = "Complete all the objectives in Canyon",
    id = 129005, badge = "141602", published = "2020-10-13 4:31:50 PM", modified = "2022-07-27 8:59:11 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 0 && CurrentCourseUs() == 2 && (prev(CanyonObjectiveFlagsUs()) + prev(CanyonObjectiveFlagsUs()) +
                 prev(CanyonObjectiveFlagsUs()) + prev(CanyonObjectiveFlagsUs()) + prev(CanyonObjectiveFlagsUs()) + prev(CanyonObjectiveFlagsUs()) +
                 prev(bit0(0x0E01A7))) == 6 && measured((CanyonObjectiveFlagsUs() + CanyonObjectiveFlagsUs() + CanyonObjectiveFlagsUs() +
                 CanyonObjectiveFlagsUs() + CanyonObjectiveFlagsUs() + CanyonObjectiveFlagsUs() + bit0(0x0E01A7)) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 0 && CurrentCourseEu() == 2 && (prev(bit1(0x0E1D96)) + prev(bit2(0x0E1D96)) +
                 prev(bit3(0x0E1D96)) + prev(bit4(0x0E1D96)) + prev(bit5(0x0E1D96)) + prev(bit7(0x0E1D96)) +
                 prev(bit0(0x0E1D97))) == 6 && measured((bit1(0x0E1D96) + bit2(0x0E1D96) + bit3(0x0E1D96) +
                 bit4(0x0E1D96) + bit5(0x0E1D96) + bit7(0x0E1D96) + bit0(0x0E1D97)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 0 && AktuelleStreckeDe() == 2 && (prev(bit1(0x0E04EE)) + prev(bit2(0x0E04EE)) +
                 prev(bit3(0x0E04EE)) + prev(bit4(0x0E04EE)) + prev(bit5(0x0E04EE)) + prev(bit7(0x0E04EE)) +
                 prev(bit0(0x0E04EF))) == 6 && measured((bit1(0x0E04EE) + bit2(0x0E04EE) + bit3(0x0E04EE) +
                 bit4(0x0E04EE) + bit5(0x0E04EE) + bit7(0x0E04EE) + bit0(0x0E04EF)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 0 && PercorsoCorrenteIt() == 2 && (prev(bit1(0x0E04FE)) + prev(bit2(0x0E04FE)) +
                 prev(bit3(0x0E04FE)) + prev(bit4(0x0E04FE)) + prev(bit5(0x0E04FE)) + prev(bit7(0x0E04FE)) +
                 prev(bit0(0x0E04FF))) == 6 && measured((bit1(0x0E04FE) + bit2(0x0E04FE) + bit3(0x0E04FE) +
                 bit4(0x0E04FE) + bit5(0x0E04FE) + bit7(0x0E04FE) + bit0(0x0E04FF)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 0 && ParcoursCouranteFr() == 2 && (prev(bit1(0x0E0636)) + prev(bit2(0x0E0636)) +
                 prev(bit3(0x0E0636)) + prev(bit4(0x0E0636)) + prev(bit5(0x0E0636)) + prev(bit7(0x0E0636)) +
                 prev(bit0(0x0E0637))) == 6 && measured((bit1(0x0E0636) + bit2(0x0E0636) + bit3(0x0E0636) +
                 bit4(0x0E0636) + bit5(0x0E0636) + bit7(0x0E0636) + bit0(0x0E0637)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 0 && PistaActualEs() == 2 && (prev(bit1(0x0E069E)) + prev(bit2(0x0E069E)) +
                 prev(bit3(0x0E069E)) + prev(bit4(0x0E069E)) + prev(bit5(0x0E069E)) + prev(bit7(0x0E069E)) +
                 prev(bit0(0x0E069F))) == 6 && measured((bit1(0x0E069E) + bit2(0x0E069E) + bit3(0x0E069E) +
                 bit4(0x0E069E) + bit5(0x0E069E) + bit7(0x0E069E) + bit0(0x0E069F)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Funfair", points = 10,
    description = "Complete all the objectives in Funfair",
    id = 129006, badge = "141603", published = "2020-10-13 4:31:54 PM", modified = "2022-07-27 8:59:30 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 0 && CurrentCourseUs() == 3 && (prev(FunfairObjectiveFlagsUs()) + prev(FunfairObjectiveFlagsUs()) +
                 prev(FunfairObjectiveFlagsUs()) + prev(FunfairObjectiveFlagsUs()) + prev(FunfairObjectiveFlagsUs()) + prev(FunfairObjectiveFlagsUs()) +
                 prev(FunfairObjectiveFlagsUs())) == 6 && measured((FunfairObjectiveFlagsUs() + FunfairObjectiveFlagsUs() + FunfairObjectiveFlagsUs() +
                 FunfairObjectiveFlagsUs() + FunfairObjectiveFlagsUs() + FunfairObjectiveFlagsUs() + FunfairObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 0 && CurrentCourseEu() == 3 && (prev(bit1(0x0E1D9E)) + prev(bit2(0x0E1D9E)) +
                 prev(bit3(0x0E1D9E)) + prev(bit4(0x0E1D9E)) + prev(bit5(0x0E1D9E)) + prev(bit6(0x0E1D9E)) +
                 prev(bit7(0x0E1D9E))) == 6 && measured((bit1(0x0E1D9E) + bit2(0x0E1D9E) + bit3(0x0E1D9E) +
                 bit4(0x0E1D9E) + bit5(0x0E1D9E) + bit6(0x0E1D9E) + bit7(0x0E1D9E)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 0 && AktuelleStreckeDe() == 3 && (prev(bit1(0x0E04F6)) + prev(bit2(0x0E04F6)) +
                 prev(bit3(0x0E04F6)) + prev(bit4(0x0E04F6)) + prev(bit5(0x0E04F6)) + prev(bit6(0x0E04F6)) +
                 prev(bit7(0x0E04F6))) == 6 && measured((bit1(0x0E04F6) + bit2(0x0E04F6) + bit3(0x0E04F6) +
                 bit4(0x0E04F6) + bit5(0x0E04F6) + bit6(0x0E04F6) + bit7(0x0E04F6)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 0 && PercorsoCorrenteIt() == 3 && (prev(bit1(0x0E0506)) + prev(bit2(0x0E0506)) +
                 prev(bit3(0x0E0506)) + prev(bit4(0x0E0506)) + prev(bit5(0x0E0506)) + prev(bit6(0x0E0506)) +
                 prev(bit7(0x0E0506))) == 6 && measured((bit1(0x0E0506) + bit2(0x0E0506) + bit3(0x0E0506) +
                 bit4(0x0E0506) + bit5(0x0E0506) + bit6(0x0E0506) + bit7(0x0E0506)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 0 && ParcoursCouranteFr() == 3 && (prev(bit1(0x0E063E)) + prev(bit2(0x0E063E)) +
                 prev(bit3(0x0E063E)) + prev(bit4(0x0E063E)) + prev(bit5(0x0E063E)) + prev(bit6(0x0E063E)) +
                 prev(bit7(0x0E063E))) == 6 && measured((bit1(0x0E063E) + bit2(0x0E063E) + bit3(0x0E063E) +
                 bit4(0x0E063E) + bit5(0x0E063E) + bit6(0x0E063E) + bit7(0x0E063E)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 0 && PistaActualEs() == 3 && (prev(bit1(0x0E06A6)) + prev(bit2(0x0E06A6)) +
                 prev(bit3(0x0E06A6)) + prev(bit4(0x0E06A6)) + prev(bit5(0x0E06A6)) + prev(bit6(0x0E06A6)) +
                 prev(bit7(0x0E06A6))) == 6 && measured((bit1(0x0E06A6) + bit2(0x0E06A6) + bit3(0x00E0A6) +
                 bit4(0x0E06A6) + bit5(0x0E06A6) + bit6(0x0E06A6) + bit7(0x0E06A6)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Happiness Hotel", points = 10,
    description = "Complete all the objectives in Happiness Hotel",
    id = 129007, badge = "141604", published = "2020-10-13 4:32:50 PM", modified = "2022-07-27 9:00:05 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 1 && CurrentCourseUs() == 0 && (prev(HappinessHotelObjectiveFlagsUs()) + prev(HappinessHotelObjectiveFlagsUs()) +
                 prev(HappinessHotelObjectiveFlagsUs()) + prev(HappinessHotelObjectiveFlagsUs()) + prev(HappinessHotelObjectiveFlagsUs()) + prev(HappinessHotelObjectiveFlagsUs()) +
                 prev(HappinessHotelObjectiveFlagsUs())) == 6 && measured((HappinessHotelObjectiveFlagsUs() + HappinessHotelObjectiveFlagsUs() + HappinessHotelObjectiveFlagsUs() +
                 HappinessHotelObjectiveFlagsUs() + HappinessHotelObjectiveFlagsUs() + HappinessHotelObjectiveFlagsUs() + HappinessHotelObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 1 && CurrentCourseEu() == 0 && (prev(bit1(0x0E1DA6)) + prev(bit2(0x0E1DA6)) +
                 prev(bit3(0x0E1DA6)) + prev(bit4(0x0E1DA6)) + prev(bit5(0x0E1DA6)) + prev(bit6(0x0E1DA6)) +
                 prev(bit7(0x0E1DA6))) == 6 && measured((bit1(0x0E1DA6) + bit2(0x0E1DA6) + bit3(0x0E1DA6) +
                 bit4(0x0E1DA6) + bit5(0x0E1DA6) + bit6(0x0E1DA6) + bit7(0x0E1DA6)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 1 && AktuelleStreckeDe() == 0 && (prev(bit1(0x0E04FE)) + prev(bit2(0x0E04FE)) +
                 prev(bit3(0x0E04FE)) + prev(bit4(0x0E04FE)) + prev(bit5(0x0E04FE)) + prev(bit6(0x0E04FE)) +
                 prev(bit7(0x0E04FE))) == 6 && measured((bit1(0x0E04FE) + bit2(0x0E04FE) + bit3(0x0E04FE) +
                 bit4(0x0E04FE) + bit5(0x0E04FE) + bit6(0x0E04FE) + bit7(0x0E04FE)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 1 && PercorsoCorrenteIt() == 0 && (prev(bit1(0x0E050E)) + prev(bit2(0x0E050E)) +
                 prev(bit3(0x0E050E)) + prev(bit4(0x0E050E)) + prev(bit5(0x0E050E)) + prev(bit6(0x0E050E)) +
                 prev(bit7(0x0E050E))) == 6 && measured((bit1(0x0E050E) + bit2(0x0E050E) + bit3(0x0E050E) +
                 bit4(0x0E050E) + bit5(0x0E050E) + bit6(0x0E050E) + bit7(0x0E050E)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 1 && ParcoursCouranteFr() == 0 && (prev(bit1(0x0E0646)) + prev(bit2(0x0E0646)) +
                 prev(bit3(0x0E0646)) + prev(bit4(0x0E0646)) + prev(bit5(0x0E0646)) + prev(bit6(0x0E0646)) +
                 prev(bit7(0x0E0646))) == 6 && measured((bit1(0x0E0646) + bit2(0x0E0646) + bit3(0x0E0646) +
                 bit4(0x0E0646) + bit5(0x0E0646) + bit6(0x0E0646) + bit7(0x0E0646)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 1 && PistaActualEs() == 0 && (prev(bit1(0x0E06AE)) + prev(bit2(0x0E06AE)) +
                 prev(bit3(0x0E06AE)) + prev(bit4(0x0E06AE)) + prev(bit5(0x0E06AE)) + prev(bit6(0x0E06AE)) +
                 prev(bit7(0x0E06AE))) == 6 && measured((bit1(0x0E06AE) + bit2(0x0E06AE) + bit3(0x0E06AE) +
                 bit4(0x0E06AE) + bit5(0x0E06AE) + bit6(0x0E06AE) + bit7(0x0E06AE)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Mallory Gallery", points = 10,
    description = "Complete all the objectives in Mallory Gallery",
    id = 129008, badge = "141782", published = "2020-10-13 4:32:54 PM", modified = "2022-07-27 9:02:16 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 1 && CurrentCourseUs() == 1 && (prev(MalloryGalleryObjectiveFlagsUs()) + prev(MalloryGalleryObjectiveFlagsUs()) +
                 prev(MalloryGalleryObjectiveFlagsUs()) + prev(MalloryGalleryObjectiveFlagsUs()) + prev(MalloryGalleryObjectiveFlagsUs()) + prev(MalloryGalleryObjectiveFlagsUs()) +
                 prev(MalloryGalleryObjectiveFlagsUs())) == 6 && measured((MalloryGalleryObjectiveFlagsUs() + MalloryGalleryObjectiveFlagsUs() + MalloryGalleryObjectiveFlagsUs() +
                 MalloryGalleryObjectiveFlagsUs() + MalloryGalleryObjectiveFlagsUs() + MalloryGalleryObjectiveFlagsUs() + MalloryGalleryObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 1 && CurrentCourseEu() == 1 && (prev(bit1(0x0E1DAE)) + prev(bit2(0x0E1DAE)) +
                 prev(bit3(0x0E1DAE)) + prev(bit4(0x0E1DAE)) + prev(bit5(0x0E1DAE)) + prev(bit6(0x0E1DAE)) +
                 prev(bit7(0x0E1DAE))) == 6 && measured((bit1(0x0E1DAE) + bit2(0x0E1DAE) + bit3(0x0E1DAE) +
                 bit4(0x0E1DAE) + bit5(0x0E1DAE) + bit6(0x0E1DAE) + bit7(0x0E1DAE)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 1 && AktuelleStreckeDe() == 1 && (prev(bit1(0x0E0506)) + prev(bit2(0x0E0506)) +
                 prev(bit3(0x0E0506)) + prev(bit4(0x0E0506)) + prev(bit5(0x0E0506)) + prev(bit6(0x0E0506)) +
                 prev(bit7(0x0E0506))) == 6 && measured((bit1(0x0E0506) + bit2(0x0E0506) + bit3(0x0E0506) +
                 bit4(0x0E0506) + bit5(0x0E0506) + bit6(0x0E0506) + bit7(0x0E0506)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 1 && PercorsoCorrenteIt() == 1 && (prev(bit1(0x0E0516)) + prev(bit2(0x0E0516)) +
                 prev(bit3(0x0E0516)) + prev(bit4(0x0E0516)) + prev(bit5(0x0E0516)) + prev(bit6(0x0E0516)) +
                 prev(bit7(0x0E0516))) == 6 && measured((bit1(0x0E0516) + bit2(0x0E0516) + bit3(0x0E0516) +
                 bit4(0x0E0516) + bit5(0x0E0516) + bit6(0x0E0516) + bit7(0x0E0516)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 1 && ParcoursCouranteFr() == 1 && (prev(bit1(0x0E064E)) + prev(bit2(0x0E064E)) +
                 prev(bit3(0x0E064E)) + prev(bit4(0x0E064E)) + prev(bit5(0x0E064E)) + prev(bit6(0x0E064E)) +
                 prev(bit7(0x0E064E))) == 6 && measured((bit1(0x0E064E) + bit2(0x0E064E) + bit3(0x0E064E) +
                 bit4(0x0E064E) + bit5(0x0E064E) + bit6(0x0E064E) + bit7(0x0E064E)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 1 && PistaActualEs() == 1 && (prev(bit1(0x0E06B6)) + prev(bit2(0x0E06B6)) +
                 prev(bit3(0x0E06B6)) + prev(bit4(0x0E06B6)) + prev(bit5(0x0E06B6)) + prev(bit6(0x0E06B6)) +
                 prev(bit7(0x0E06B6))) == 6 && measured((bit1(0x0E06B6) + bit2(0x0E06B6) + bit3(0x0E06B6) +
                 bit4(0x0E06B6) + bit5(0x0E06B6) + bit6(0x0E06B6) + bit7(0x0E06B6)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Trafalgar Square", points = 10,
    description = "Complete all the objectives in Trafalgar Square",
    id = 129009, badge = "141962", published = "2020-10-13 4:32:57 PM", modified = "2022-07-27 9:02:32 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 1 && CurrentCourseUs() == 2 && (prev(TrafalgarSquareObjectiveFlagsUs()) + prev(TrafalgarSquareObjectiveFlagsUs()) +
                 prev(TrafalgarSquareObjectiveFlagsUs()) + prev(TrafalgarSquareObjectiveFlagsUs()) + prev(TrafalgarSquareObjectiveFlagsUs()) + prev(TrafalgarSquareObjectiveFlagsUs()) +
                 prev(bit0(0x0E01C7))) == 6 && measured((TrafalgarSquareObjectiveFlagsUs() + TrafalgarSquareObjectiveFlagsUs() + TrafalgarSquareObjectiveFlagsUs() +
                 TrafalgarSquareObjectiveFlagsUs() + TrafalgarSquareObjectiveFlagsUs() + TrafalgarSquareObjectiveFlagsUs() + bit0(0x0E01C7)) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 1 && CurrentCourseEu() == 2 && (prev(bit1(0x0E1DB6)) + prev(bit2(0x0E1DB6)) +
                 prev(bit3(0x0E1DB6)) + prev(bit4(0x0E1DB6)) + prev(bit5(0x0E1DB6)) + prev(bit7(0x0E1DB6)) +
                 prev(bit0(0x0E1DB7))) == 6 && measured((bit1(0x0E1DB6) + bit2(0x0E1DB6) + bit3(0x0E1DB6) +
                 bit4(0x0E1DB6) + bit5(0x0E1DB6) + bit7(0x0E1DB6) + bit0(0x0E1DB7)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 1 && AktuelleStreckeDe() == 2 && (prev(bit1(0x0E050E)) + prev(bit2(0x0E050E)) +
                 prev(bit3(0x0E050E)) + prev(bit4(0x0E050E)) + prev(bit5(0x0E050E)) + prev(bit7(0x0E050E)) +
                 prev(bit0(0x0E050F))) == 6 && measured((bit1(0x0E050E) + bit2(0x0E050E) + bit3(0x0E050E) +
                 bit4(0x0E050E) + bit5(0x0E050E) + bit7(0x0E050E) + bit0(0x0E050F)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 1 && PercorsoCorrenteIt() == 2 && (prev(bit1(0x0E051E)) + prev(bit2(0x0E051E)) +
                 prev(bit3(0x0E051E)) + prev(bit4(0x0E051E)) + prev(bit5(0x0E051E)) + prev(bit7(0x0E051E)) +
                 prev(bit0(0x0E051F))) == 6 && measured((bit1(0x0E051E) + bit2(0x0E051E) + bit3(0x0E051E) +
                 bit4(0x0E051E) + bit5(0x0E051E) + bit7(0x0E051E) + bit0(0x0E051F)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 1 && ParcoursCouranteFr() == 2 && (prev(bit1(0x0E0656)) + prev(bit2(0x0E0656)) +
                 prev(bit3(0x0E0656)) + prev(bit4(0x0E0656)) + prev(bit5(0x0E0656)) + prev(bit7(0x0E0656)) +
                 prev(bit0(0x0E0657))) == 6 && measured((bit1(0x0E0656) + bit2(0x0E0656) + bit3(0x0E0656) +
                 bit4(0x0E0656) + bit5(0x0E0656) + bit7(0x0E0656) + bit0(0x0E0657)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 1 && PistaActualEs() == 2 && (prev(bit1(0x0E06BE)) + prev(bit2(0x0E06BE)) +
                 prev(bit3(0x0E06BE)) + prev(bit4(0x0E06BE)) + prev(bit5(0x0E06BE)) + prev(bit7(0x0E06BE)) +
                 prev(bit0(0x0E06BF))) == 6 && measured((bit1(0x0E06BE) + bit2(0x0E06BE) + bit3(0x0E06BE) +
                 bit4(0x0E06BE) + bit5(0x0E06BE) + bit7(0x0E06BE) + bit0(0x0E06BF)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Restaurant", points = 10,
    description = "Complete all the objectives in Restaurant",
    id = 129010, badge = "141964", published = "2020-10-13 4:33:00 PM", modified = "2022-07-27 9:03:52 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 1 && CurrentCourseUs() == 3 && (prev(RestaurantObjectiveFlagsUs()) + prev(RestaurantObjectiveFlagsUs()) +
                 prev(RestaurantObjectiveFlagsUs()) + prev(RestaurantObjectiveFlagsUs()) + prev(RestaurantObjectiveFlagsUs()) + prev(RestaurantObjectiveFlagsUs()) +
                 prev(RestaurantObjectiveFlagsUs())) == 6 && measured((RestaurantObjectiveFlagsUs() + RestaurantObjectiveFlagsUs() + RestaurantObjectiveFlagsUs() +
                 RestaurantObjectiveFlagsUs() + RestaurantObjectiveFlagsUs() + RestaurantObjectiveFlagsUs() + RestaurantObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 1 && CurrentCourseEu() == 3 && (prev(bit1(0x0E1DBE)) + prev(bit2(0x0E1DBE)) +
                 prev(bit3(0x0E1DBE)) + prev(bit4(0x0E1DBE)) + prev(bit5(0x0E1DBE)) + prev(bit6(0x0E1DBE)) +
                 prev(bit7(0x0E1DBE))) == 6 && measured((bit1(0x0E1DBE) + bit2(0x0E1DBE) + bit3(0x0E1DBE) +
                 bit4(0x0E1DBE) + bit5(0x0E1DBE) + bit6(0x0E1DBE) + bit7(0x0E1DBE)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 1 && AktuelleStreckeDe() == 3 && (prev(bit1(0x0E0516)) + prev(bit2(0x0E0516)) +
                 prev(bit3(0x0E0516)) + prev(bit4(0x0E0516)) + prev(bit5(0x0E0516)) + prev(bit6(0x0E0516)) +
                 prev(bit7(0x0E0516))) == 6 && measured((bit1(0x0E0516) + bit2(0x0E0516) + bit3(0x0E0516) +
                 bit4(0x0E0516) + bit5(0x0E0516) + bit6(0x0E0516) + bit7(0x0E0516)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 1 && PercorsoCorrenteIt() == 3 && (prev(bit1(0x0E0526)) + prev(bit2(0x0E0526)) +
                 prev(bit3(0x0E0526)) + prev(bit4(0x0E0526)) + prev(bit5(0x0E0526)) + prev(bit6(0x0E0526)) +
                 prev(bit7(0x0E0526))) == 6 && measured((bit1(0x0E0526) + bit2(0x0E0526) + bit3(0x0E0526) +
                 bit4(0x0E0526) + bit5(0x0E0526) + bit6(0x0E0526) + bit7(0x0E0526)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 1 && ParcoursCouranteFr() == 3 && (prev(bit1(0x0E065E)) + prev(bit2(0x0E065E)) +
                 prev(bit3(0x0E065E)) + prev(bit4(0x0E065E)) + prev(bit5(0x0E065E)) + prev(bit6(0x0E065E)) +
                 prev(bit7(0x0E065E))) == 6 && measured((bit1(0x0E065E) + bit2(0x0E065E) + bit3(0x0E065E) +
                 bit4(0x0E065E) + bit5(0x0E065E) + bit6(0x0E065E) + bit7(0x0E065E)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 1 && PistaActualEs() == 3 && (prev(bit1(0x0E06C6)) + prev(bit2(0x0E06C6)) +
                 prev(bit3(0x0E06C6)) + prev(bit4(0x0E06C6)) + prev(bit5(0x0E06C6)) + prev(bit6(0x0E06C6)) +
                 prev(bit7(0x0E06C6))) == 6 && measured((bit1(0x0E06C6) + bit2(0x0E06C6) + bit3(0x00E0C6) +
                 bit4(0x0E06C6) + bit5(0x0E06C6) + bit6(0x0E06C6) + bit7(0x0E06C6)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Central Park", points = 10,
    description = "Complete all the objectives in Central Park",
    id = 129011, badge = "141967", published = "2020-10-13 4:33:04 PM", modified = "2022-07-27 9:04:22 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 2 && CurrentCourseUs() == 0 && (prev(CentralParkObjectiveFlagsUs()) + prev(CentralParkObjectiveFlagsUs()) +
                 prev(CentralParkObjectiveFlagsUs()) + prev(CentralParkObjectiveFlagsUs()) + prev(CentralParkObjectiveFlagsUs()) + prev(CentralParkObjectiveFlagsUs())) == 5 && 
                measured((CentralParkObjectiveFlagsUs() + CentralParkObjectiveFlagsUs() + CentralParkObjectiveFlagsUs() + CentralParkObjectiveFlagsUs() + CentralParkObjectiveFlagsUs() +
                 CentralParkObjectiveFlagsUs()) == 6, when=MusicVolumeUs() <= 15 && SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 &&
                 PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 || CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 ||
                 CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 && SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 &&
                 SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 2 && CurrentCourseEu() == 0 && (prev(bit1(0x0E1DC6)) + prev(bit2(0x0E1DC6)) +
                 prev(bit3(0x0E1DC6)) + prev(bit4(0x0E1DC6)) + prev(bit5(0x0E1DC6)) + prev(bit7(0x0E1DC6))) == 5 && 
                measured((bit1(0x0E1DC6) + bit2(0x0E1DC6) + bit3(0x0E1DC6) + bit4(0x0E1DC6) + bit5(0x0E1DC6) +
                 bit7(0x0E1DC6)) == 6, when=MusicVolumeEu() <= 15 && SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 &&
                 PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 || CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 ||
                 CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 && byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 &&
                 byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 2 && AktuelleStreckeDe() == 0 && (prev(bit1(0x0E051E)) + prev(bit2(0x0E051E)) +
                 prev(bit3(0x0E051E)) + prev(bit4(0x0E051E)) + prev(bit5(0x0E051E)) + prev(bit7(0x0E051E))) == 5 && 
                measured((bit1(0x0E051E) + bit2(0x0E051E) + bit3(0x0E051E) + bit4(0x0E051E) + bit5(0x0E051E) +
                 bit7(0x0E051E)) == 6, when=MusiklautstärkeDe() <= 15 && TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 &&
                 PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 && byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 &&
                 byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 2 && PercorsoCorrenteIt() == 0 && (prev(bit1(0x0E052E)) + prev(bit2(0x0E052E)) +
                 prev(bit3(0x0E052E)) + prev(bit4(0x0E052E)) + prev(bit5(0x0E052E)) + prev(bit7(0x0E052E))) == 5 && 
                measured((bit1(0x0E052E) + bit2(0x0E052E) + bit3(0x0E052E) + bit4(0x0E052E) + bit5(0x0E052E) +
                 bit7(0x0E052E)) == 6, when=VolumeDellaMusicaIt() <= 15 && VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 &&
                 PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 && byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 &&
                 byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 2 && ParcoursCouranteFr() == 0 && (prev(bit1(0x0E0666)) + prev(bit2(0x0E0666)) +
                 prev(bit3(0x0E0666)) + prev(bit4(0x0E0666)) + prev(bit5(0x0E0666)) + prev(bit7(0x0E0666))) == 5 && 
                measured((bit1(0x0E0666) + bit2(0x0E0666) + bit3(0x0E0666) + bit4(0x0E0666) + bit5(0x0E0666) +
                 bit7(0x0E0666)) == 6, when=byte(0x0BA010) <= 15 && byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 &&
                 PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 && byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 &&
                 byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 2 && PistaActualEs() == 0 && (prev(bit1(0x0E06CE)) + prev(bit2(0x0E06CE)) +
                 prev(bit3(0x0E06CE)) + prev(bit4(0x0E06CE)) + prev(bit5(0x0E06CE)) + prev(bit7(0x0E06CE))) == 5 && 
                measured((bit1(0x0E06CE) + bit2(0x0E06CE) + bit3(0x0E06CE) + bit4(0x0E06CE) + bit5(0x0E06CE) +
                 bit7(0x0E06CE)) == 6, when=VolumenDeMúsicaEs() <= 15 && VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 &&
                 PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 && byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 &&
                 byte(0x0E068F) == 1)))
)

achievement(
    title = "100% New York City", points = 10,
    description = "Complete all the objectives in New York City",
    id = 129012, badge = "141968", published = "2020-10-13 4:33:07 PM", modified = "2022-07-27 9:06:15 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 2 && CurrentCourseUs() == 1 && (prev(NewYorkCityObjectiveFlagsUs()) + prev(NewYorkCityObjectiveFlagsUs()) +
                 prev(NewYorkCityObjectiveFlagsUs()) + prev(NewYorkCityObjectiveFlagsUs()) + prev(NewYorkCityObjectiveFlagsUs()) + prev(NewYorkCityObjectiveFlagsUs()) +
                 prev(NewYorkCityObjectiveFlagsUs())) == 6 && measured((NewYorkCityObjectiveFlagsUs() + NewYorkCityObjectiveFlagsUs() + NewYorkCityObjectiveFlagsUs() +
                 NewYorkCityObjectiveFlagsUs() + NewYorkCityObjectiveFlagsUs() + NewYorkCityObjectiveFlagsUs() + NewYorkCityObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 2 && CurrentCourseEu() == 1 && (prev(bit1(0x0E1DCE)) + prev(bit2(0x0E1DCE)) +
                 prev(bit3(0x0E1DCE)) + prev(bit4(0x0E1DCE)) + prev(bit5(0x0E1DCE)) + prev(bit6(0x0E1DCE)) +
                 prev(bit7(0x0E1DCE))) == 6 && measured((bit1(0x0E1DCE) + bit2(0x0E1DCE) + bit3(0x0E1DCE) +
                 bit4(0x0E1DCE) + bit5(0x0E1DCE) + bit6(0x0E1DCE) + bit7(0x0E1DCE)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 2 && AktuelleStreckeDe() == 1 && (prev(bit1(0x0E0526)) + prev(bit2(0x0E0526)) +
                 prev(bit3(0x0E0526)) + prev(bit4(0x0E0526)) + prev(bit5(0x0E0526)) + prev(bit6(0x0E0526)) +
                 prev(bit7(0x0E0526))) == 6 && measured((bit1(0x0E0526) + bit2(0x0E0526) + bit3(0x0E0526) +
                 bit4(0x0E0526) + bit5(0x0E0526) + bit6(0x0E0526) + bit7(0x0E0526)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 2 && PercorsoCorrenteIt() == 1 && (prev(bit1(0x0E0536)) + prev(bit2(0x0E0536)) +
                 prev(bit3(0x0E0536)) + prev(bit4(0x0E0536)) + prev(bit5(0x0E0536)) + prev(bit6(0x0E0536)) +
                 prev(bit7(0x0E0536))) == 6 && measured((bit1(0x0E0536) + bit2(0x0E0536) + bit3(0x0E0536) +
                 bit4(0x0E0536) + bit5(0x0E0536) + bit6(0x0E0536) + bit7(0x0E0536)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 2 && ParcoursCouranteFr() == 1 && (prev(bit1(0x0E066E)) + prev(bit2(0x0E066E)) +
                 prev(bit3(0x0E066E)) + prev(bit4(0x0E066E)) + prev(bit5(0x0E066E)) + prev(bit6(0x0E066E)) +
                 prev(bit7(0x0E066E))) == 6 && measured((bit1(0x0E066E) + bit2(0x0E066E) + bit3(0x0E066E) +
                 bit4(0x0E066E) + bit5(0x0E066E) + bit6(0x0E066E) + bit7(0x0E066E)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 2 && PistaActualEs() == 1 && (prev(bit1(0x0E06D6)) + prev(bit2(0x0E06D6)) +
                 prev(bit3(0x0E06D6)) + prev(bit4(0x0E06D6)) + prev(bit5(0x0E06D6)) + prev(bit6(0x0E06D6)) +
                 prev(bit7(0x0E06D6))) == 6 && measured((bit1(0x0E06D6) + bit2(0x0E06D6) + bit3(0x0E06D6) +
                 bit4(0x0E06D6) + bit5(0x0E06D6) + bit6(0x0E06D6) + bit7(0x0E06D6)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Theatre", points = 10,
    description = "Complete all the objectives in Theatre",
    id = 129013, badge = "141969", published = "2020-10-13 4:33:11 PM", modified = "2022-07-27 9:06:35 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 2 && CurrentCourseUs() == 2 && (prev(TheatreObjectiveFlagsUs()) + prev(TheatreObjectiveFlagsUs()) +
                 prev(TheatreObjectiveFlagsUs()) + prev(TheatreObjectiveFlagsUs()) + prev(TheatreObjectiveFlagsUs()) + prev(TheatreObjectiveFlagsUs()) +
                 prev(bit0(0x0E01E7))) == 6 && measured((TheatreObjectiveFlagsUs() + TheatreObjectiveFlagsUs() + TheatreObjectiveFlagsUs() +
                 TheatreObjectiveFlagsUs() + TheatreObjectiveFlagsUs() + TheatreObjectiveFlagsUs() + bit0(0x0E01E7)) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 2 && CurrentCourseEu() == 2 && (prev(bit1(0x0E1DD6)) + prev(bit2(0x0E1DD6)) +
                 prev(bit3(0x0E1DD6)) + prev(bit4(0x0E1DD6)) + prev(bit5(0x0E1DD6)) + prev(bit7(0x0E1DD6)) +
                 prev(bit0(0x0E1DD7))) == 6 && measured((bit1(0x0E1DD6) + bit2(0x0E1DD6) + bit3(0x0E1DD6) +
                 bit4(0x0E1DD6) + bit5(0x0E1DD6) + bit7(0x0E1DD6) + bit0(0x0E1DD7)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 2 && AktuelleStreckeDe() == 2 && (prev(bit1(0x0E052E)) + prev(bit2(0x0E052E)) +
                 prev(bit3(0x0E052E)) + prev(bit4(0x0E052E)) + prev(bit5(0x0E052E)) + prev(bit7(0x0E052E)) +
                 prev(bit0(0x0E052F))) == 6 && measured((bit1(0x0E052E) + bit2(0x0E052E) + bit3(0x0E052E) +
                 bit4(0x0E052E) + bit5(0x0E052E) + bit7(0x0E052E) + bit0(0x0E052F)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 2 && PercorsoCorrenteIt() == 2 && (prev(bit1(0x0E053E)) + prev(bit2(0x0E053E)) +
                 prev(bit3(0x0E053E)) + prev(bit4(0x0E053E)) + prev(bit5(0x0E053E)) + prev(bit7(0x0E053E)) +
                 prev(bit0(0x0E053F))) == 6 && measured((bit1(0x0E053E) + bit2(0x0E053E) + bit3(0x0E053E) +
                 bit4(0x0E053E) + bit5(0x0E053E) + bit7(0x0E053E) + bit0(0x0E053F)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 2 && ParcoursCouranteFr() == 2 && (prev(bit1(0x0E0676)) + prev(bit2(0x0E0676)) +
                 prev(bit3(0x0E0676)) + prev(bit4(0x0E0676)) + prev(bit5(0x0E0676)) + prev(bit7(0x0E0676)) +
                 prev(bit0(0x0E0677))) == 6 && measured((bit1(0x0E0676) + bit2(0x0E0676) + bit3(0x0E0676) +
                 bit4(0x0E0676) + bit5(0x0E0676) + bit7(0x0E0676) + bit0(0x0E0677)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 2 && PistaActualEs() == 2 && (prev(bit1(0x0E06DE)) + prev(bit2(0x0E06DE)) +
                 prev(bit3(0x0E06DE)) + prev(bit4(0x0E06DE)) + prev(bit5(0x0E06DE)) + prev(bit7(0x0E06DE)) +
                 prev(bit0(0x0E06DF))) == 6 && measured((bit1(0x0E06DE) + bit2(0x0E06DE) + bit3(0x0E06DE) +
                 bit4(0x0E06DE) + bit5(0x0E06DE) + bit7(0x0E06DE) + bit0(0x0E06DF)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Diner", points = 10,
    description = "Complete all the objectives in Diner",
    id = 129014, badge = "141971", published = "2020-10-13 4:33:16 PM", modified = "2022-07-27 9:07:37 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 2 && CurrentCourseUs() == 3 && (prev(DinerObjectiveFlagsUs()) + prev(DinerObjectiveFlagsUs()) +
                 prev(DinerObjectiveFlagsUs()) + prev(DinerObjectiveFlagsUs()) + prev(DinerObjectiveFlagsUs()) + prev(DinerObjectiveFlagsUs()) +
                 prev(DinerObjectiveFlagsUs())) == 6 && measured((DinerObjectiveFlagsUs() + DinerObjectiveFlagsUs() + DinerObjectiveFlagsUs() +
                 DinerObjectiveFlagsUs() + DinerObjectiveFlagsUs() + DinerObjectiveFlagsUs() + DinerObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 2 && CurrentCourseEu() == 3 && (prev(bit1(0x0E1DDE)) + prev(bit2(0x0E1DDE)) +
                 prev(bit3(0x0E1DDE)) + prev(bit4(0x0E1DDE)) + prev(bit5(0x0E1DDE)) + prev(bit6(0x0E1DDE)) +
                 prev(bit7(0x0E1DDE))) == 6 && measured((bit1(0x0E1DDE) + bit2(0x0E1DDE) + bit3(0x0E1DDE) +
                 bit4(0x0E1DDE) + bit5(0x0E1DDE) + bit6(0x0E1DDE) + bit7(0x0E1DDE)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 2 && AktuelleStreckeDe() == 3 && (prev(bit1(0x0E0536)) + prev(bit2(0x0E0536)) +
                 prev(bit3(0x0E0536)) + prev(bit4(0x0E0536)) + prev(bit5(0x0E0536)) + prev(bit6(0x0E0536)) +
                 prev(bit7(0x0E0536))) == 6 && measured((bit1(0x0E0536) + bit2(0x0E0536) + bit3(0x0E0536) +
                 bit4(0x0E0536) + bit5(0x0E0536) + bit6(0x0E0536) + bit7(0x0E0536)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 2 && PercorsoCorrenteIt() == 3 && (prev(bit1(0x0E0546)) + prev(bit2(0x0E0546)) +
                 prev(bit3(0x0E0546)) + prev(bit4(0x0E0546)) + prev(bit5(0x0E0546)) + prev(bit6(0x0E0546)) +
                 prev(bit7(0x0E0546))) == 6 && measured((bit1(0x0E0546) + bit2(0x0E0546) + bit3(0x0E0546) +
                 bit4(0x0E0546) + bit5(0x0E0546) + bit6(0x0E0546) + bit7(0x0E0546)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 2 && ParcoursCouranteFr() == 3 && (prev(bit1(0x0E067E)) + prev(bit2(0x0E067E)) +
                 prev(bit3(0x0E067E)) + prev(bit4(0x0E067E)) + prev(bit5(0x0E067E)) + prev(bit6(0x0E067E)) +
                 prev(bit7(0x0E067E))) == 6 && measured((bit1(0x0E067E) + bit2(0x0E067E) + bit3(0x0E067E) +
                 bit4(0x0E067E) + bit5(0x0E067E) + bit6(0x0E067E) + bit7(0x0E067E)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 2 && PistaActualEs() == 3 && (prev(bit1(0x0E06E6)) + prev(bit2(0x0E06E6)) +
                 prev(bit3(0x0E06E6)) + prev(bit4(0x0E06E6)) + prev(bit5(0x0E06E6)) + prev(bit6(0x0E06E6)) +
                 prev(bit7(0x0E06E6))) == 6 && measured((bit1(0x0E06E6) + bit2(0x0E06E6) + bit3(0x00E0E6) +
                 bit4(0x0E06E6) + bit5(0x0E06E6) + bit6(0x0E06E6) + bit7(0x0E06E6)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Old London Town", points = 10,
    description = "Complete all the objectives in Old London Town",
    id = 129015, badge = "141976", published = "2020-10-13 4:33:20 PM", modified = "2022-07-27 9:07:52 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 3 && CurrentCourseUs() == 0 && (prev(OldLondonTownObjectiveFlagsUs()) + prev(OldLondonTownObjectiveFlagsUs()) +
                 prev(OldLondonTownObjectiveFlagsUs()) + prev(OldLondonTownObjectiveFlagsUs()) + prev(OldLondonTownObjectiveFlagsUs()) + prev(OldLondonTownObjectiveFlagsUs()) +
                 prev(OldLondonTownObjectiveFlagsUs())) == 6 && measured((OldLondonTownObjectiveFlagsUs() + OldLondonTownObjectiveFlagsUs() + OldLondonTownObjectiveFlagsUs() +
                 OldLondonTownObjectiveFlagsUs() + OldLondonTownObjectiveFlagsUs() + OldLondonTownObjectiveFlagsUs() + OldLondonTownObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 3 && CurrentCourseEu() == 0 && (prev(bit1(0x0E1DE6)) + prev(bit2(0x0E1DE6)) +
                 prev(bit3(0x0E1DE6)) + prev(bit4(0x0E1DE6)) + prev(bit5(0x0E1DE6)) + prev(bit6(0x0E1DE6)) +
                 prev(bit7(0x0E1DE6))) == 6 && measured((bit1(0x0E1DE6) + bit2(0x0E1DE6) + bit3(0x0E1DE6) +
                 bit4(0x0E1DE6) + bit5(0x0E1DE6) + bit6(0x0E1DE6) + bit7(0x0E1DE6)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 3 && AktuelleStreckeDe() == 0 && (prev(bit1(0x0E053E)) + prev(bit2(0x0E053E)) +
                 prev(bit3(0x0E053E)) + prev(bit4(0x0E053E)) + prev(bit5(0x0E053E)) + prev(bit6(0x0E053E)) +
                 prev(bit7(0x0E053E))) == 6 && measured((bit1(0x0E053E) + bit2(0x0E053E) + bit3(0x0E053E) +
                 bit4(0x0E053E) + bit5(0x0E053E) + bit6(0x0E053E) + bit7(0x0E053E)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 3 && PercorsoCorrenteIt() == 0 && (prev(bit1(0x0E054E)) + prev(bit2(0x0E054E)) +
                 prev(bit3(0x0E054E)) + prev(bit4(0x0E054E)) + prev(bit5(0x0E054E)) + prev(bit6(0x0E054E)) +
                 prev(bit7(0x0E054E))) == 6 && measured((bit1(0x0E054E) + bit2(0x0E054E) + bit3(0x0E054E) +
                 bit4(0x0E054E) + bit5(0x0E054E) + bit6(0x0E054E) + bit7(0x0E054E)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 3 && ParcoursCouranteFr() == 0 && (prev(bit1(0x0E0686)) + prev(bit2(0x0E0686)) +
                 prev(bit3(0x0E0686)) + prev(bit4(0x0E0686)) + prev(bit5(0x0E0686)) + prev(bit6(0x0E0686)) +
                 prev(bit7(0x0E0686))) == 6 && measured((bit1(0x0E0686) + bit2(0x0E0686) + bit3(0x0E0686) +
                 bit4(0x0E0686) + bit5(0x0E0686) + bit6(0x0E0686) + bit7(0x0E0686)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 3 && PistaActualEs() == 0 && (prev(bit1(0x0E06EE)) + prev(bit2(0x0E06EE)) +
                 prev(bit3(0x0E06EE)) + prev(bit4(0x0E06EE)) + prev(bit5(0x0E06EE)) + prev(bit6(0x0E06EE)) +
                 prev(bit7(0x0E06EE))) == 6 && measured((bit1(0x0E06EE) + bit2(0x0E06EE) + bit3(0x0E06EE) +
                 bit4(0x0E06EE) + bit5(0x0E06EE) + bit6(0x0E06EE) + bit7(0x0E06EE)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Graveyard", points = 10,
    description = "Complete all the objectives in Graveyard",
    id = 129016, badge = "141981", published = "2020-10-13 4:33:23 PM", modified = "2022-07-27 9:08:11 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 3 && CurrentCourseUs() == 1 && (prev(GraveyardObjectiveFlagsUs()) + prev(GraveyardObjectiveFlagsUs()) +
                 prev(GraveyardObjectiveFlagsUs()) + prev(GraveyardObjectiveFlagsUs()) + prev(GraveyardObjectiveFlagsUs()) + prev(GraveyardObjectiveFlagsUs()) +
                 prev(GraveyardObjectiveFlagsUs())) == 6 && measured((GraveyardObjectiveFlagsUs() + GraveyardObjectiveFlagsUs() + GraveyardObjectiveFlagsUs() +
                 GraveyardObjectiveFlagsUs() + GraveyardObjectiveFlagsUs() + GraveyardObjectiveFlagsUs() + GraveyardObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 3 && CurrentCourseEu() == 1 && (prev(bit1(0x0E1DEE)) + prev(bit2(0x0E1DEE)) +
                 prev(bit3(0x0E1DEE)) + prev(bit4(0x0E1DEE)) + prev(bit5(0x0E1DEE)) + prev(bit6(0x0E1DEE)) +
                 prev(bit7(0x0E1DEE))) == 6 && measured((bit1(0x0E1DEE) + bit2(0x0E1DEE) + bit3(0x0E1DEE) +
                 bit4(0x0E1DEE) + bit5(0x0E1DEE) + bit6(0x0E1DEE) + bit7(0x0E1DEE)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 3 && AktuelleStreckeDe() == 1 && (prev(bit1(0x0E0546)) + prev(bit2(0x0E0546)) +
                 prev(bit3(0x0E0546)) + prev(bit4(0x0E0546)) + prev(bit5(0x0E0546)) + prev(bit6(0x0E0546)) +
                 prev(bit7(0x0E0546))) == 6 && measured((bit1(0x0E0546) + bit2(0x0E0546) + bit3(0x0E0546) +
                 bit4(0x0E0546) + bit5(0x0E0546) + bit6(0x0E0546) + bit7(0x0E0546)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 3 && PercorsoCorrenteIt() == 1 && (prev(bit1(0x0E0556)) + prev(bit2(0x0E0556)) +
                 prev(bit3(0x0E0556)) + prev(bit4(0x0E0556)) + prev(bit5(0x0E0556)) + prev(bit6(0x0E0556)) +
                 prev(bit7(0x0E0556))) == 6 && measured((bit1(0x0E0556) + bit2(0x0E0556) + bit3(0x0E0556) +
                 bit4(0x0E0556) + bit5(0x0E0556) + bit6(0x0E0556) + bit7(0x0E0556)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 3 && ParcoursCouranteFr() == 1 && (prev(FlagsDeObjetivosDeCiénagaEs()) + prev(FlagsDeObjetivosDeCiénagaEs()) +
                 prev(FlagsDeObjetivosDeCiénagaEs()) + prev(FlagsDeObjetivosDeCiénagaEs()) + prev(FlagsDeObjetivosDeCiénagaEs()) + prev(FlagsDeObjetivosDeCiénagaEs()) +
                 prev(FlagsDeObjetivosDeCiénagaEs())) == 6 && measured((FlagsDeObjetivosDeCiénagaEs() + FlagsDeObjetivosDeCiénagaEs() + FlagsDeObjetivosDeCiénagaEs() +
                 FlagsDeObjetivosDeCiénagaEs() + FlagsDeObjetivosDeCiénagaEs() + FlagsDeObjetivosDeCiénagaEs() + FlagsDeObjetivosDeCiénagaEs()) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 3 && PistaActualEs() == 1 && (prev(bit1(0x0E06F6)) + prev(bit2(0x0E06F6)) +
                 prev(bit3(0x0E06F6)) + prev(bit4(0x0E06F6)) + prev(bit5(0x0E06F6)) + prev(bit6(0x0E06F6)) +
                 prev(bit7(0x0E06F6))) == 6 && measured((bit1(0x0E06F6) + bit2(0x0E06F6) + bit3(0x0E06F6) +
                 bit4(0x0E06F6) + bit5(0x0E06F6) + bit6(0x0E06F6) + bit7(0x0E06F6)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Chamber", points = 10,
    description = "Complete all the objectives in Chamber",
    id = 129017, badge = "141982", published = "2020-10-13 4:33:36 PM", modified = "2022-07-27 9:09:12 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 3 && CurrentCourseUs() == 2 && (prev(ChamberObjectiveFlagsUs()) + prev(ChamberObjectiveFlagsUs()) +
                 prev(ChamberObjectiveFlagsUs()) + prev(ChamberObjectiveFlagsUs()) + prev(ChamberObjectiveFlagsUs()) + prev(ChamberObjectiveFlagsUs()) +
                 prev(bit0(0x0E0207))) == 6 && measured((ChamberObjectiveFlagsUs() + ChamberObjectiveFlagsUs() + ChamberObjectiveFlagsUs() +
                 ChamberObjectiveFlagsUs() + ChamberObjectiveFlagsUs() + ChamberObjectiveFlagsUs() + bit0(0x0E0207)) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 3 && CurrentCourseEu() == 2 && (prev(bit1(0x0E1DF6)) + prev(bit2(0x0E1DF6)) +
                 prev(bit3(0x0E1DF6)) + prev(bit4(0x0E1DF6)) + prev(bit5(0x0E1DF6)) + prev(bit7(0x0E1DF6)) +
                 prev(bit0(0x0E1DF7))) == 6 && measured((bit1(0x0E1DF6) + bit2(0x0E1DF6) + bit3(0x0E1DF6) +
                 bit4(0x0E1DF6) + bit5(0x0E1DF6) + bit7(0x0E1DF6) + bit0(0x0E1DF7)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 3 && AktuelleStreckeDe() == 2 && (prev(bit1(0x0E054E)) + prev(bit2(0x0E054E)) +
                 prev(bit3(0x0E054E)) + prev(bit4(0x0E054E)) + prev(bit5(0x0E054E)) + prev(bit7(0x0E054E)) +
                 prev(bit0(0x0E054F))) == 6 && measured((bit1(0x0E054E) + bit2(0x0E054E) + bit3(0x0E054E) +
                 bit4(0x0E054E) + bit5(0x0E054E) + bit7(0x0E054E) + bit0(0x0E054F)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 3 && PercorsoCorrenteIt() == 2 && (prev(bit1(0x0E055E)) + prev(bit2(0x0E055E)) +
                 prev(bit3(0x0E055E)) + prev(bit4(0x0E055E)) + prev(bit5(0x0E055E)) + prev(bit7(0x0E055E)) +
                 prev(bit0(0x0E055F))) == 6 && measured((bit1(0x0E055E) + bit2(0x0E055E) + bit3(0x0E055E) +
                 bit4(0x0E055E) + bit5(0x0E055E) + bit7(0x0E055E) + bit0(0x0E055F)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 3 && ParcoursCouranteFr() == 2 && (prev(bit1(0x0E0696)) + prev(bit2(0x0E0696)) +
                 prev(bit3(0x0E0696)) + prev(bit4(0x0E0696)) + prev(bit5(0x0E0696)) + prev(bit7(0x0E0696)) +
                 prev(bit0(0x0E0697))) == 6 && measured((bit1(0x0E0696) + bit2(0x0E0696) + bit3(0x0E0696) +
                 bit4(0x0E0696) + bit5(0x0E0696) + bit7(0x0E0696) + bit0(0x0E0697)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 3 && PistaActualEs() == 2 && (prev(bit1(0x0E06FE)) + prev(bit2(0x0E06FE)) +
                 prev(bit3(0x0E06FE)) + prev(bit4(0x0E06FE)) + prev(bit5(0x0E06FE)) + prev(bit7(0x0E06FE)) +
                 prev(bit0(0x0E06FF))) == 6 && measured((bit1(0x0E06FE) + bit2(0x0E06FE) + bit3(0x0E06FE) +
                 bit4(0x0E06FE) + bit5(0x0E06FE) + bit7(0x0E06FE) + bit0(0x0E06FF)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Rooftops", points = 10,
    description = "Complete all the objectives in Rooftops",
    id = 129018, badge = "141984", published = "2020-10-13 4:33:40 PM", modified = "2022-07-27 9:09:31 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 3 && CurrentCourseUs() == 3 && (prev(RooftopsObjectiveFlagsUs()) + prev(RooftopsObjectiveFlagsUs()) +
                 prev(RooftopsObjectiveFlagsUs()) + prev(RooftopsObjectiveFlagsUs()) + prev(RooftopsObjectiveFlagsUs()) + prev(RooftopsObjectiveFlagsUs()) +
                 prev(RooftopsObjectiveFlagsUs())) == 6 && measured((RooftopsObjectiveFlagsUs() + RooftopsObjectiveFlagsUs() + RooftopsObjectiveFlagsUs() +
                 RooftopsObjectiveFlagsUs() + RooftopsObjectiveFlagsUs() + RooftopsObjectiveFlagsUs() + RooftopsObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 3 && CurrentCourseEu() == 3 && (prev(bit1(0x0E1DFE)) + prev(bit2(0x0E1DFE)) +
                 prev(bit3(0x0E1DFE)) + prev(bit4(0x0E1DFE)) + prev(bit5(0x0E1DFE)) + prev(bit6(0x0E1DFE)) +
                 prev(bit7(0x0E1DFE))) == 6 && measured((bit1(0x0E1DFE) + bit2(0x0E1DFE) + bit3(0x0E1DFE) +
                 bit4(0x0E1DFE) + bit5(0x0E1DFE) + bit6(0x0E1DFE) + bit7(0x0E1DFE)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 3 && AktuelleStreckeDe() == 3 && (prev(bit1(0x0E0556)) + prev(bit2(0x0E0556)) +
                 prev(bit3(0x0E0556)) + prev(bit4(0x0E0556)) + prev(bit5(0x0E0556)) + prev(bit6(0x0E0556)) +
                 prev(bit7(0x0E0556))) == 6 && measured((bit1(0x0E0556) + bit2(0x0E0556) + bit3(0x0E0556) +
                 bit4(0x0E0556) + bit5(0x0E0556) + bit6(0x0E0556) + bit7(0x0E0556)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 3 && PercorsoCorrenteIt() == 3 && (prev(bit1(0x0E0566)) + prev(bit2(0x0E0566)) +
                 prev(bit3(0x0E0566)) + prev(bit4(0x0E0566)) + prev(bit5(0x0E0566)) + prev(bit6(0x0E0566)) +
                 prev(bit7(0x0E0566))) == 6 && measured((bit1(0x0E0566) + bit2(0x0E0566) + bit3(0x0E0566) +
                 bit4(0x0E0566) + bit5(0x0E0566) + bit6(0x0E0566) + bit7(0x0E0566)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 3 && ParcoursCouranteFr() == 3 && (prev(bit1(0x0E069E)) + prev(bit2(0x0E069E)) +
                 prev(bit3(0x0E069E)) + prev(bit4(0x0E069E)) + prev(bit5(0x0E069E)) + prev(bit6(0x0E069E)) +
                 prev(bit7(0x0E069E))) == 6 && measured((bit1(0x0E069E) + bit2(0x0E069E) + bit3(0x0E069E) +
                 bit4(0x0E069E) + bit5(0x0E069E) + bit6(0x0E069E) + bit7(0x0E069E)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 3 && PistaActualEs() == 3 && (prev(bit1(0x0E0706)) + prev(bit2(0x0E0706)) +
                 prev(bit3(0x0E0706)) + prev(bit4(0x0E0706)) + prev(bit5(0x0E0706)) + prev(bit6(0x0E0706)) +
                 prev(bit7(0x0E0706))) == 6 && measured((bit1(0x0E0706) + bit2(0x0E0706) + bit3(0x00E706) +
                 bit4(0x0E0706) + bit5(0x0E0706) + bit6(0x0E0706) + bit7(0x0E0706)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Dock", points = 10,
    description = "Complete all the objectives in Dock",
    id = 129019, badge = "141985", published = "2020-10-13 4:33:43 PM", modified = "2022-07-27 9:09:56 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 4 && CurrentCourseUs() == 0 && (prev(DockObjectiveFlagsUs()) + prev(DockObjectiveFlagsUs()) +
                 prev(DockObjectiveFlagsUs()) + prev(DockObjectiveFlagsUs()) + prev(DockObjectiveFlagsUs()) + prev(DockObjectiveFlagsUs()) +
                 prev(DockObjectiveFlagsUs())) == 6 && measured((DockObjectiveFlagsUs() + DockObjectiveFlagsUs() + DockObjectiveFlagsUs() +
                 DockObjectiveFlagsUs() + DockObjectiveFlagsUs() + DockObjectiveFlagsUs() + DockObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 4 && CurrentCourseEu() == 0 && (prev(bit1(0x0E1E06)) + prev(bit2(0x0E1E06)) +
                 prev(bit3(0x0E1E06)) + prev(bit4(0x0E1E06)) + prev(bit5(0x0E1E06)) + prev(bit6(0x0E1E06)) +
                 prev(bit7(0x0E1E06))) == 6 && measured((bit1(0x0E1E06) + bit2(0x0E1E06) + bit3(0x0E1E06) +
                 bit4(0x0E1E06) + bit5(0x0E1E06) + bit6(0x0E1E06) + bit7(0x0E1E06)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 4 && AktuelleStreckeDe() == 0 && (prev(bit1(0x0E055E)) + prev(bit2(0x0E055E)) +
                 prev(bit3(0x0E055E)) + prev(bit4(0x0E055E)) + prev(bit5(0x0E055E)) + prev(bit6(0x0E055E)) +
                 prev(bit7(0x0E055E))) == 6 && measured((bit1(0x0E055E) + bit2(0x0E055E) + bit3(0x0E055E) +
                 bit4(0x0E055E) + bit5(0x0E055E) + bit6(0x0E055E) + bit7(0x0E055E)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 4 && PercorsoCorrenteIt() == 0 && (prev(bit1(0x0E056E)) + prev(bit2(0x0E056E)) +
                 prev(bit3(0x0E056E)) + prev(bit4(0x0E056E)) + prev(bit5(0x0E056E)) + prev(bit6(0x0E056E)) +
                 prev(bit7(0x0E056E))) == 6 && measured((bit1(0x0E056E) + bit2(0x0E056E) + bit3(0x0E056E) +
                 bit4(0x0E056E) + bit5(0x0E056E) + bit6(0x0E056E) + bit7(0x0E056E)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 4 && ParcoursCouranteFr() == 0 && (prev(bit1(0x0E06A6)) + prev(bit2(0x0E06A6)) +
                 prev(bit3(0x0E06A6)) + prev(bit4(0x0E06A6)) + prev(bit5(0x0E06A6)) + prev(bit6(0x0E06A6)) +
                 prev(bit7(0x0E06A6))) == 6 && measured((bit1(0x0E06A6) + bit2(0x0E06A6) + bit3(0x0E06A6) +
                 bit4(0x0E06A6) + bit5(0x0E06A6) + bit6(0x0E06A6) + bit7(0x0E06A6)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 4 && PistaActualEs() == 0 && (prev(bit1(0x0E070E)) + prev(bit2(0x0E070E)) +
                 prev(bit3(0x0E070E)) + prev(bit4(0x0E070E)) + prev(bit5(0x0E070E)) + prev(bit6(0x0E070E)) +
                 prev(bit7(0x0E070E))) == 6 && measured((bit1(0x0E070E) + bit2(0x0E070E) + bit3(0x0E070E) +
                 bit4(0x0E070E) + bit5(0x0E070E) + bit6(0x0E070E) + bit7(0x0E070E)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Treasure Island", points = 10,
    description = "Complete all the objectives in Treasure Island",
    id = 129020, badge = "141987", published = "2020-10-13 4:33:46 PM", modified = "2022-07-27 9:10:14 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 4 && CurrentCourseUs() == 1 && (prev(TreasureIslandObjectiveFlagsUs()) + prev(TreasureIslandObjectiveFlagsUs()) +
                 prev(TreasureIslandObjectiveFlagsUs()) + prev(TreasureIslandObjectiveFlagsUs()) + prev(TreasureIslandObjectiveFlagsUs()) + prev(TreasureIslandObjectiveFlagsUs()) +
                 prev(TreasureIslandObjectiveFlagsUs())) == 6 && measured((TreasureIslandObjectiveFlagsUs() + TreasureIslandObjectiveFlagsUs() + TreasureIslandObjectiveFlagsUs() +
                 TreasureIslandObjectiveFlagsUs() + TreasureIslandObjectiveFlagsUs() + TreasureIslandObjectiveFlagsUs() + TreasureIslandObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 4 && CurrentCourseEu() == 1 && (prev(bit1(0x0E1E0E)) + prev(bit2(0x0E1E0E)) +
                 prev(bit3(0x0E1E0E)) + prev(bit4(0x0E1E0E)) + prev(bit5(0x0E1E0E)) + prev(bit6(0x0E1E0E)) +
                 prev(bit7(0x0E1E0E))) == 6 && measured((bit1(0x0E1E0E) + bit2(0x0E1E0E) + bit3(0x0E1E0E) +
                 bit4(0x0E1E0E) + bit5(0x0E1E0E) + bit6(0x0E1E0E) + bit7(0x0E1E0E)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 4 && AktuelleStreckeDe() == 1 && (prev(bit1(0x0E0566)) + prev(bit2(0x0E0566)) +
                 prev(bit3(0x0E0566)) + prev(bit4(0x0E0566)) + prev(bit5(0x0E0566)) + prev(bit6(0x0E0566)) +
                 prev(bit7(0x0E0566))) == 6 && measured((bit1(0x0E0566) + bit2(0x0E0566) + bit3(0x0E0566) +
                 bit4(0x0E0566) + bit5(0x0E0566) + bit6(0x0E0566) + bit7(0x0E0566)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 4 && PercorsoCorrenteIt() == 1 && (prev(bit1(0x0E0576)) + prev(bit2(0x0E0576)) +
                 prev(bit3(0x0E0576)) + prev(bit4(0x0E0576)) + prev(bit5(0x0E0576)) + prev(bit6(0x0E0576)) +
                 prev(bit7(0x0E0576))) == 6 && measured((bit1(0x0E0576) + bit2(0x0E0576) + bit3(0x0E0576) +
                 bit4(0x0E0576) + bit5(0x0E0576) + bit6(0x0E0576) + bit7(0x0E0576)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 4 && ParcoursCouranteFr() == 1 && (prev(bit1(0x0E06AE)) + prev(bit2(0x0E06AE)) +
                 prev(bit3(0x0E06AE)) + prev(bit4(0x0E06AE)) + prev(bit5(0x0E06AE)) + prev(bit6(0x0E06AE)) +
                 prev(bit7(0x0E06AE))) == 6 && measured((bit1(0x0E06AE) + bit2(0x0E06AE) + bit3(0x0E06AE) +
                 bit4(0x0E06AE) + bit5(0x0E06AE) + bit6(0x0E06AE) + bit7(0x0E06AE)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 4 && PistaActualEs() == 1 && (prev(bit1(0x0E0716)) + prev(bit2(0x0E0716)) +
                 prev(bit3(0x0E0716)) + prev(bit4(0x0E0716)) + prev(bit5(0x0E0716)) + prev(bit6(0x0E0716)) +
                 prev(bit7(0x0E0716))) == 6 && measured((bit1(0x0E0716) + bit2(0x0E0716) + bit3(0x0E0716) +
                 bit4(0x0E0716) + bit5(0x0E0716) + bit6(0x0E0716) + bit7(0x0E0716)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Lagoon", points = 10,
    description = "Complete all the objectives in Lagoon",
    id = 129021, badge = "141988", published = "2020-10-13 4:33:49 PM", modified = "2022-07-27 9:10:47 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 4 && CurrentCourseUs() == 2 && (prev(LagoonObjectiveFlagsUs()) + prev(LagoonObjectiveFlagsUs()) +
                 prev(LagoonObjectiveFlagsUs()) + prev(LagoonObjectiveFlagsUs()) + prev(LagoonObjectiveFlagsUs()) + prev(LagoonObjectiveFlagsUs()) +
                 prev(bit0(0x0E0227))) == 6 && measured((LagoonObjectiveFlagsUs() + LagoonObjectiveFlagsUs() + LagoonObjectiveFlagsUs() +
                 LagoonObjectiveFlagsUs() + LagoonObjectiveFlagsUs() + LagoonObjectiveFlagsUs() + bit0(0x0E0227)) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 4 && CurrentCourseEu() == 2 && (prev(bit1(0x0E1E16)) + prev(bit2(0x0E1E16)) +
                 prev(bit3(0x0E1E16)) + prev(bit4(0x0E1E16)) + prev(bit5(0x0E1E16)) + prev(bit7(0x0E1E16)) +
                 prev(bit0(0x0E1E17))) == 6 && measured((bit1(0x0E1E16) + bit2(0x0E1E16) + bit3(0x0E1E16) +
                 bit4(0x0E1E16) + bit5(0x0E1E16) + bit7(0x0E1E16) + bit0(0x0E1E17)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 4 && AktuelleStreckeDe() == 2 && (prev(bit1(0x0E056E)) + prev(bit2(0x0E056E)) +
                 prev(bit3(0x0E056E)) + prev(bit4(0x0E056E)) + prev(bit5(0x0E056E)) + prev(bit7(0x0E056E)) +
                 prev(bit0(0x0E056F))) == 6 && measured((bit1(0x0E056E) + bit2(0x0E056E) + bit3(0x0E056E) +
                 bit4(0x0E056E) + bit5(0x0E056E) + bit7(0x0E056E) + bit0(0x0E056F)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 4 && PercorsoCorrenteIt() == 2 && (prev(bit1(0x0E057E)) + prev(bit2(0x0E057E)) +
                 prev(bit3(0x0E057E)) + prev(bit4(0x0E057E)) + prev(bit5(0x0E057E)) + prev(bit7(0x0E057E)) +
                 prev(bit0(0x0E057F))) == 6 && measured((bit1(0x0E057E) + bit2(0x0E057E) + bit3(0x0E057E) +
                 bit4(0x0E057E) + bit5(0x0E057E) + bit7(0x0E057E) + bit0(0x0E057F)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 4 && ParcoursCouranteFr() == 2 && (prev(bit1(0x0E06B6)) + prev(bit2(0x0E06B6)) +
                 prev(bit3(0x0E06B6)) + prev(bit4(0x0E06B6)) + prev(bit5(0x0E06B6)) + prev(bit7(0x0E06B6)) +
                 prev(bit0(0x0E06B7))) == 6 && measured((bit1(0x0E06B6) + bit2(0x0E06B6) + bit3(0x0E06B6) +
                 bit4(0x0E06B6) + bit5(0x0E06B6) + bit7(0x0E06B6) + bit0(0x0E06B7)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 4 && PistaActualEs() == 2 && (prev(bit1(0x0E071E)) + prev(bit2(0x0E071E)) +
                 prev(bit3(0x0E071E)) + prev(bit4(0x0E071E)) + prev(bit5(0x0E071E)) + prev(bit7(0x0E071E)) +
                 prev(bit0(0x0E071F))) == 6 && measured((bit1(0x0E071E) + bit2(0x0E071E) + bit3(0x0E071E) +
                 bit4(0x0E071E) + bit5(0x0E071E) + bit7(0x0E071E) + bit0(0x0E071F)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Mountain", points = 10,
    description = "Complete all the objectives in Mountain",
    id = 129022, badge = "141989", published = "2020-10-13 4:33:52 PM", modified = "2022-07-27 9:12:19 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 4 && CurrentCourseUs() == 3 && (prev(MountainObjectiveFlagsUs()) + prev(MountainObjectiveFlagsUs()) +
                 prev(MountainObjectiveFlagsUs()) + prev(MountainObjectiveFlagsUs()) + prev(MountainObjectiveFlagsUs()) + prev(MountainObjectiveFlagsUs()) +
                 prev(MountainObjectiveFlagsUs())) == 6 && measured((MountainObjectiveFlagsUs() + MountainObjectiveFlagsUs() + MountainObjectiveFlagsUs() +
                 MountainObjectiveFlagsUs() + MountainObjectiveFlagsUs() + MountainObjectiveFlagsUs() + MountainObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 4 && CurrentCourseEu() == 3 && (prev(bit1(0x0E1E1E)) + prev(bit2(0x0E1E1E)) +
                 prev(bit3(0x0E1E1E)) + prev(bit4(0x0E1E1E)) + prev(bit5(0x0E1E1E)) + prev(bit6(0x0E1E1E)) +
                 prev(bit7(0x0E1E1E))) == 6 && measured((bit1(0x0E1E1E) + bit2(0x0E1E1E) + bit3(0x0E1E1E) +
                 bit4(0x0E1E1E) + bit5(0x0E1E1E) + bit6(0x0E1E1E) + bit7(0x0E1E1E)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 4 && AktuelleStreckeDe() == 3 && (prev(bit1(0x0E0576)) + prev(bit2(0x0E0576)) +
                 prev(bit3(0x0E0576)) + prev(bit4(0x0E0576)) + prev(bit5(0x0E0576)) + prev(bit6(0x0E0576)) +
                 prev(bit7(0x0E0576))) == 6 && measured((bit1(0x0E0576) + bit2(0x0E0576) + bit3(0x0E0576) +
                 bit4(0x0E0576) + bit5(0x0E0576) + bit6(0x0E0576) + bit7(0x0E0576)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 4 && PercorsoCorrenteIt() == 3 && (prev(bit1(0x0E0586)) + prev(bit2(0x0E0586)) +
                 prev(bit3(0x0E0586)) + prev(bit4(0x0E0586)) + prev(bit5(0x0E0586)) + prev(bit6(0x0E0586)) +
                 prev(bit7(0x0E0586))) == 6 && measured((bit1(0x0E0586) + bit2(0x0E0586) + bit3(0x0E0586) +
                 bit4(0x0E0586) + bit5(0x0E0586) + bit6(0x0E0586) + bit7(0x0E0586)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 4 && ParcoursCouranteFr() == 3 && (prev(bit1(0x0E06BE)) + prev(bit2(0x0E06BE)) +
                 prev(bit3(0x0E06BE)) + prev(bit4(0x0E06BE)) + prev(bit5(0x0E06BE)) + prev(bit6(0x0E06BE)) +
                 prev(bit7(0x0E06BE))) == 6 && measured((bit1(0x0E06BE) + bit2(0x0E06BE) + bit3(0x0E06BE) +
                 bit4(0x0E06BE) + bit5(0x0E06BE) + bit6(0x0E06BE) + bit7(0x0E06BE)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 4 && PistaActualEs() == 3 && (prev(bit1(0x0E0726)) + prev(bit2(0x0E0726)) +
                 prev(bit3(0x0E0726)) + prev(bit4(0x0E0726)) + prev(bit5(0x0E0726)) + prev(bit6(0x0E0726)) +
                 prev(bit7(0x0E0726))) == 6 && measured((bit1(0x0E0726) + bit2(0x0E0726) + bit3(0x00E726) +
                 bit4(0x0E0726) + bit5(0x0E0726) + bit6(0x0E0726) + bit7(0x0E0726)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Secret Base", points = 10,
    description = "Complete all the objectives in Secret Base",
    id = 129023, badge = "141990", published = "2020-10-13 4:34:05 PM", modified = "2022-07-27 9:12:41 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 5 && CurrentCourseUs() == 0 && (prev(SecretBaseObjectiveFlagsUs()) + prev(SecretBaseObjectiveFlagsUs()) +
                 prev(SecretBaseObjectiveFlagsUs()) + prev(SecretBaseObjectiveFlagsUs()) + prev(SecretBaseObjectiveFlagsUs()) + prev(SecretBaseObjectiveFlagsUs()) +
                 prev(SecretBaseObjectiveFlagsUs())) == 6 && measured((SecretBaseObjectiveFlagsUs() + SecretBaseObjectiveFlagsUs() + SecretBaseObjectiveFlagsUs() +
                 SecretBaseObjectiveFlagsUs() + SecretBaseObjectiveFlagsUs() + SecretBaseObjectiveFlagsUs() + SecretBaseObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 5 && CurrentCourseEu() == 0 && (prev(bit1(0x0E1E26)) + prev(bit2(0x0E1E26)) +
                 prev(bit3(0x0E1E26)) + prev(bit4(0x0E1E26)) + prev(bit5(0x0E1E26)) + prev(bit6(0x0E1E26)) +
                 prev(bit7(0x0E1E26))) == 6 && measured((bit1(0x0E1E26) + bit2(0x0E1E26) + bit3(0x0E1E26) +
                 bit4(0x0E1E26) + bit5(0x0E1E26) + bit6(0x0E1E26) + bit7(0x0E1E26)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 5 && AktuelleStreckeDe() == 0 && (prev(bit1(0x0E057E)) + prev(bit2(0x0E057E)) +
                 prev(bit3(0x0E057E)) + prev(bit4(0x0E057E)) + prev(bit5(0x0E057E)) + prev(bit6(0x0E057E)) +
                 prev(bit7(0x0E057E))) == 6 && measured((bit1(0x0E057E) + bit2(0x0E057E) + bit3(0x0E057E) +
                 bit4(0x0E057E) + bit5(0x0E057E) + bit6(0x0E057E) + bit7(0x0E057E)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 5 && PercorsoCorrenteIt() == 0 && (prev(bit1(0x0E058E)) + prev(bit2(0x0E058E)) +
                 prev(bit3(0x0E058E)) + prev(bit4(0x0E058E)) + prev(bit5(0x0E058E)) + prev(bit6(0x0E058E)) +
                 prev(bit7(0x0E058E))) == 6 && measured((bit1(0x0E058E) + bit2(0x0E058E) + bit3(0x0E058E) +
                 bit4(0x0E058E) + bit5(0x0E058E) + bit6(0x0E058E) + bit7(0x0E058E)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 5 && ParcoursCouranteFr() == 0 && (prev(bit1(0x0E06C6)) + prev(bit2(0x0E06C6)) +
                 prev(bit3(0x0E06C6)) + prev(bit4(0x0E06C6)) + prev(bit5(0x0E06C6)) + prev(bit6(0x0E06C6)) +
                 prev(bit7(0x0E06C6))) == 6 && measured((bit1(0x0E06C6) + bit2(0x0E06C6) + bit3(0x0E06C6) +
                 bit4(0x0E06C6) + bit5(0x0E06C6) + bit6(0x0E06C6) + bit7(0x0E06C6)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 5 && PistaActualEs() == 0 && (prev(bit1(0x0E072E)) + prev(bit2(0x0E072E)) +
                 prev(bit3(0x0E072E)) + prev(bit4(0x0E072E)) + prev(bit5(0x0E072E)) + prev(bit6(0x0E072E)) +
                 prev(bit7(0x0E072E))) == 6 && measured((bit1(0x0E072E) + bit2(0x0E072E) + bit3(0x0E072E) +
                 bit4(0x0E072E) + bit5(0x0E072E) + bit6(0x0E072E) + bit7(0x0E072E)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Cape Doom", points = 10,
    description = "Complete all the objectives in Cape Doom",
    id = 129024, badge = "141992", published = "2020-10-13 4:34:09 PM", modified = "2022-07-27 9:12:59 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 5 && CurrentCourseUs() == 1 && (prev(CapeDoomObjectiveFlagsUs()) + prev(CapeDoomObjectiveFlagsUs()) +
                 prev(CapeDoomObjectiveFlagsUs()) + prev(CapeDoomObjectiveFlagsUs()) + prev(CapeDoomObjectiveFlagsUs()) + prev(CapeDoomObjectiveFlagsUs()) +
                 prev(CapeDoomObjectiveFlagsUs())) == 6 && measured((CapeDoomObjectiveFlagsUs() + CapeDoomObjectiveFlagsUs() + CapeDoomObjectiveFlagsUs() +
                 CapeDoomObjectiveFlagsUs() + CapeDoomObjectiveFlagsUs() + CapeDoomObjectiveFlagsUs() + CapeDoomObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 5 && CurrentCourseEu() == 1 && (prev(bit1(0x0E1E2E)) + prev(bit2(0x0E1E2E)) +
                 prev(bit3(0x0E1E2E)) + prev(bit4(0x0E1E2E)) + prev(bit5(0x0E1E2E)) + prev(bit6(0x0E1E2E)) +
                 prev(bit7(0x0E1E2E))) == 6 && measured((bit1(0x0E1E2E) + bit2(0x0E1E2E) + bit3(0x0E1E2E) +
                 bit4(0x0E1E2E) + bit5(0x0E1E2E) + bit6(0x0E1E2E) + bit7(0x0E1E2E)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 5 && AktuelleStreckeDe() == 1 && (prev(bit1(0x0E0586)) + prev(bit2(0x0E0586)) +
                 prev(bit3(0x0E0586)) + prev(bit4(0x0E0586)) + prev(bit5(0x0E0586)) + prev(bit6(0x0E0586)) +
                 prev(bit7(0x0E0586))) == 6 && measured((bit1(0x0E0586) + bit2(0x0E0586) + bit3(0x0E0586) +
                 bit4(0x0E0586) + bit5(0x0E0586) + bit6(0x0E0586) + bit7(0x0E0586)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 5 && PercorsoCorrenteIt() == 1 && (prev(bit1(0x0E0596)) + prev(bit2(0x0E0596)) +
                 prev(bit3(0x0E0596)) + prev(bit4(0x0E0596)) + prev(bit5(0x0E0596)) + prev(bit6(0x0E0596)) +
                 prev(bit7(0x0E0596))) == 6 && measured((bit1(0x0E0596) + bit2(0x0E0596) + bit3(0x0E0596) +
                 bit4(0x0E0596) + bit5(0x0E0596) + bit6(0x0E0596) + bit7(0x0E0596)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 5 && ParcoursCouranteFr() == 1 && (prev(bit1(0x0E06CE)) + prev(bit2(0x0E06CE)) +
                 prev(bit3(0x0E06CE)) + prev(bit4(0x0E06CE)) + prev(bit5(0x0E06CE)) + prev(bit6(0x0E06CE)) +
                 prev(bit7(0x0E06CE))) == 6 && measured((bit1(0x0E06CE) + bit2(0x0E06CE) + bit3(0x0E06CE) +
                 bit4(0x0E06CE) + bit5(0x0E06CE) + bit6(0x0E06CE) + bit7(0x0E06CE)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 5 && PistaActualEs() == 1 && (prev(bit1(0x0E0736)) + prev(bit2(0x0E0736)) +
                 prev(bit3(0x0E0736)) + prev(bit4(0x0E0736)) + prev(bit5(0x0E0736)) + prev(bit6(0x0E0736)) +
                 prev(bit7(0x0E0736))) == 6 && measured((bit1(0x0E0736) + bit2(0x0E0736) + bit3(0x0E0736) +
                 bit4(0x0E0736) + bit5(0x0E0736) + bit6(0x0E0736) + bit7(0x0E0736)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Laboratory", points = 10,
    description = "Complete all the objectives in Laboratory",
    id = 129025, badge = "141994", published = "2020-10-13 4:34:12 PM", modified = "2022-07-27 9:13:15 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 5 && CurrentCourseUs() == 2 && (prev(LaboratoryObjectiveFlagsUs()) + prev(LaboratoryObjectiveFlagsUs()) +
                 prev(LaboratoryObjectiveFlagsUs()) + prev(LaboratoryObjectiveFlagsUs()) + prev(LaboratoryObjectiveFlagsUs()) + prev(LaboratoryObjectiveFlagsUs()) +
                 prev(bit0(0x0E0247))) == 6 && measured((LaboratoryObjectiveFlagsUs() + LaboratoryObjectiveFlagsUs() + LaboratoryObjectiveFlagsUs() +
                 LaboratoryObjectiveFlagsUs() + LaboratoryObjectiveFlagsUs() + LaboratoryObjectiveFlagsUs() + bit0(0x0E0247)) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 5 && CurrentCourseEu() == 2 && (prev(bit1(0x0E1E36)) + prev(bit2(0x0E1E36)) +
                 prev(bit3(0x0E1E36)) + prev(bit4(0x0E1E36)) + prev(bit5(0x0E1E36)) + prev(bit7(0x0E1E36)) +
                 prev(bit0(0x0E1E37))) == 6 && measured((bit1(0x0E1E36) + bit2(0x0E1E36) + bit3(0x0E1E36) +
                 bit4(0x0E1E36) + bit5(0x0E1E36) + bit7(0x0E1E36) + bit0(0x0E1E37)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 5 && AktuelleStreckeDe() == 2 && (prev(bit1(0x0E058E)) + prev(bit2(0x0E058E)) +
                 prev(bit3(0x0E058E)) + prev(bit4(0x0E058E)) + prev(bit5(0x0E058E)) + prev(bit7(0x0E058E)) +
                 prev(bit0(0x0E058F))) == 6 && measured((bit1(0x0E058E) + bit2(0x0E058E) + bit3(0x0E058E) +
                 bit4(0x0E058E) + bit5(0x0E058E) + bit7(0x0E058E) + bit0(0x0E058F)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 5 && PercorsoCorrenteIt() == 2 && (prev(bit1(0x0E059E)) + prev(bit2(0x0E059E)) +
                 prev(bit3(0x0E059E)) + prev(bit4(0x0E059E)) + prev(bit5(0x0E059E)) + prev(bit7(0x0E059E)) +
                 prev(bit0(0x0E059F))) == 6 && measured((bit1(0x0E059E) + bit2(0x0E059E) + bit3(0x0E059E) +
                 bit4(0x0E059E) + bit5(0x0E059E) + bit7(0x0E059E) + bit0(0x0E059F)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 5 && ParcoursCouranteFr() == 2 && (prev(bit1(0x0E06D6)) + prev(bit2(0x0E06D6)) +
                 prev(bit3(0x0E06D6)) + prev(bit4(0x0E06D6)) + prev(bit5(0x0E06D6)) + prev(bit7(0x0E06D6)) +
                 prev(bit0(0x0E06D7))) == 6 && measured((bit1(0x0E06D6) + bit2(0x0E06D6) + bit3(0x0E06D6) +
                 bit4(0x0E06D6) + bit5(0x0E06D6) + bit7(0x0E06D6) + bit0(0x0E06D7)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 5 && PistaActualEs() == 2 && (prev(bit1(0x0E073E)) + prev(bit2(0x0E073E)) +
                 prev(bit3(0x0E073E)) + prev(bit4(0x0E073E)) + prev(bit5(0x0E073E)) + prev(bit7(0x0E073E)) +
                 prev(bit0(0x0E073F))) == 6 && measured((bit1(0x0E073E) + bit2(0x0E073E) + bit3(0x0E073E) +
                 bit4(0x0E073E) + bit5(0x0E073E) + bit7(0x0E073E) + bit0(0x0E073F)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Muppet Labs", points = 10,
    description = "Complete all the objectives in Muppet Labs",
    id = 129026, badge = "141996", published = "2020-10-13 4:34:16 PM", modified = "2022-07-27 9:13:51 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 5 && CurrentCourseUs() == 3 && (prev(MuppetLabsObjectiveFlagsUs()) + prev(MuppetLabsObjectiveFlagsUs()) +
                 prev(MuppetLabsObjectiveFlagsUs()) + prev(MuppetLabsObjectiveFlagsUs()) + prev(MuppetLabsObjectiveFlagsUs()) + prev(MuppetLabsObjectiveFlagsUs()) +
                 prev(MuppetLabsObjectiveFlagsUs())) == 6 && measured((MuppetLabsObjectiveFlagsUs() + MuppetLabsObjectiveFlagsUs() + MuppetLabsObjectiveFlagsUs() +
                 MuppetLabsObjectiveFlagsUs() + MuppetLabsObjectiveFlagsUs() + MuppetLabsObjectiveFlagsUs() + MuppetLabsObjectiveFlagsUs()) == 7, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 5 && CurrentCourseEu() == 3 && (prev(bit1(0x0E1E3E)) + prev(bit2(0x0E1E3E)) +
                 prev(bit3(0x0E1E3E)) + prev(bit4(0x0E1E3E)) + prev(bit5(0x0E1E3E)) + prev(bit6(0x0E1E3E)) +
                 prev(bit7(0x0E1E3E))) == 6 && measured((bit1(0x0E1E3E) + bit2(0x0E1E3E) + bit3(0x0E1E3E) +
                 bit4(0x0E1E3E) + bit5(0x0E1E3E) + bit6(0x0E1E3E) + bit7(0x0E1E3E)) == 7, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 5 && AktuelleStreckeDe() == 3 && (prev(bit1(0x0E0596)) + prev(bit2(0x0E0596)) +
                 prev(bit3(0x0E0596)) + prev(bit4(0x0E0596)) + prev(bit5(0x0E0596)) + prev(bit6(0x0E0596)) +
                 prev(bit7(0x0E0596))) == 6 && measured((bit1(0x0E0596) + bit2(0x0E0596) + bit3(0x0E0596) +
                 bit4(0x0E0596) + bit5(0x0E0596) + bit6(0x0E0596) + bit7(0x0E0596)) == 7, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 5 && PercorsoCorrenteIt() == 3 && (prev(bit1(0x0E05A6)) + prev(bit2(0x0E05A6)) +
                 prev(bit3(0x0E05A6)) + prev(bit4(0x0E05A6)) + prev(bit5(0x0E05A6)) + prev(bit6(0x0E05A6)) +
                 prev(bit7(0x0E05A6))) == 6 && measured((bit1(0x0E05A6) + bit2(0x0E05A6) + bit3(0x0E05A6) +
                 bit4(0x0E05A6) + bit5(0x0E05A6) + bit6(0x0E05A6) + bit7(0x0E05A6)) == 7, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 5 && ParcoursCouranteFr() == 3 && (prev(bit1(0x0E06DE)) + prev(bit2(0x0E06DE)) +
                 prev(bit3(0x0E06DE)) + prev(bit4(0x0E06DE)) + prev(bit5(0x0E06DE)) + prev(bit6(0x0E06DE)) +
                 prev(bit7(0x0E06DE))) == 6 && measured((bit1(0x0E06DE) + bit2(0x0E06DE) + bit3(0x0E06DE) +
                 bit4(0x0E06DE) + bit5(0x0E06DE) + bit6(0x0E06DE) + bit7(0x0E06DE)) == 7, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 5 && PistaActualEs() == 3 && (prev(bit1(0x0E0746)) + prev(bit2(0x0E0746)) +
                 prev(bit3(0x0E0746)) + prev(bit4(0x0E0746)) + prev(bit5(0x0E0746)) + prev(bit6(0x0E0746)) +
                 prev(bit7(0x0E0746))) == 6 && measured((bit1(0x0E0746) + bit2(0x0E0746) + bit3(0x00E746) +
                 bit4(0x0E0746) + bit5(0x0E0746) + bit6(0x0E0746) + bit7(0x0E0746)) == 7, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Studio", points = 10,
    description = "Complete all the objectives in Studio",
    id = 129027, badge = "141998", published = "2020-10-13 4:34:19 PM", modified = "2022-07-27 9:14:35 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 6 && CurrentCourseUs() == 0 && (prev(StudioObjectiveFlagsUs()) + prev(StudioObjectiveFlagsUs()) +
                 prev(StudioObjectiveFlagsUs()) + prev(StudioObjectiveFlagsUs()) + prev(StudioObjectiveFlagsUs())) == 4 && measured((StudioObjectiveFlagsUs() +
                 StudioObjectiveFlagsUs() + StudioObjectiveFlagsUs() + StudioObjectiveFlagsUs() + StudioObjectiveFlagsUs()) == 5, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 6 && CurrentCourseEu() == 0 && (prev(bit1(0x0E1E46)) + prev(bit2(0x0E1E46)) +
                 prev(bit3(0x0E1E46)) + prev(bit4(0x0E1E46)) + prev(bit7(0x0E1E46))) == 4 && measured((bit1(0x0E1E46) +
                 bit2(0x0E1E46) + bit3(0x0E1E46) + bit4(0x0E1E46) + bit7(0x0E1E46)) == 5, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 6 && AktuelleStreckeDe() == 0 && (prev(bit1(0x0E059E)) + prev(bit2(0x0E059E)) +
                 prev(bit3(0x0E059E)) + prev(bit4(0x0E059E)) + prev(bit7(0x0E059E))) == 4 && measured((bit1(0x0E059E) +
                 bit2(0x0E059E) + bit3(0x0E059E) + bit4(0x0E059E) + bit7(0x0E059E)) == 5, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 6 && PercorsoCorrenteIt() == 0 && (prev(bit1(0x0E05AE)) + prev(bit2(0x0E05AE)) +
                 prev(bit3(0x0E05AE)) + prev(bit4(0x0E05AE)) + prev(bit7(0x0E05AE))) == 4 && measured((bit1(0x0E05AE) +
                 bit2(0x0E05AE) + bit3(0x0E05AE) + bit4(0x0E05AE) + bit7(0x0E05AE)) == 5, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 6 && ParcoursCouranteFr() == 0 && (prev(bit1(0x0E06E6)) + prev(bit2(0x0E06E6)) +
                 prev(bit3(0x0E06E6)) + prev(bit4(0x0E06E6)) + prev(bit7(0x0E06E6))) == 4 && measured((bit1(0x0E06E6) +
                 bit2(0x0E06E6) + bit3(0x0E06E6) + bit4(0x0E06E6) + bit7(0x0E06E6)) == 5, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 6 && PistaActualEs() == 0 && (prev(bit1(0x0E074E)) + prev(bit2(0x0E074E)) +
                 prev(bit3(0x0E074E)) + prev(bit4(0x0E074E)) + prev(bit7(0x0E074E))) == 4 && measured((bit1(0x0E074E) +
                 bit2(0x0E074E) + bit3(0x0E074E) + bit4(0x0E074E) + bit7(0x0E074E)) == 5, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Arches", points = 10,
    description = "Complete all the objectives in Arches",
    id = 129028, badge = "142000", published = "2020-10-13 4:34:23 PM", modified = "2022-07-27 9:14:48 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 6 && CurrentCourseUs() == 1 && (prev(ArchesObjectiveFlagsUs()) + prev(ArchesObjectiveFlagsUs()) +
                 prev(ArchesObjectiveFlagsUs()) + prev(ArchesObjectiveFlagsUs()) + prev(ArchesObjectiveFlagsUs())) == 4 && measured((ArchesObjectiveFlagsUs() +
                 ArchesObjectiveFlagsUs() + ArchesObjectiveFlagsUs() + ArchesObjectiveFlagsUs() + ArchesObjectiveFlagsUs()) == 5, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 6 && CurrentCourseEu() == 1 && (prev(bit1(0x0E1E4E)) + prev(bit2(0x0E1E4E)) +
                 prev(bit3(0x0E1E4E)) + prev(bit4(0x0E1E4E)) + prev(bit7(0x0E1E4E))) == 4 && measured((bit1(0x0E1E4E) +
                 bit2(0x0E1E4E) + bit3(0x0E1E4E) + bit4(0x0E1E4E) + bit7(0x0E1E4E)) == 5, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 6 && AktuelleStreckeDe() == 1 && (prev(bit1(0x0E05A6)) + prev(bit2(0x0E05A6)) +
                 prev(bit3(0x0E05A6)) + prev(bit4(0x0E05A6)) + prev(bit7(0x0E05A6))) == 4 && measured((bit1(0x0E05A6) +
                 bit2(0x0E05A6) + bit3(0x0E05A6) + bit4(0x0E05A6) + bit7(0x0E05A6)) == 5, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 6 && PercorsoCorrenteIt() == 1 && (prev(bit1(0x0E05B6)) + prev(bit2(0x0E05B6)) +
                 prev(bit3(0x0E05B6)) + prev(bit4(0x0E05B6)) + prev(bit7(0x0E05B6))) == 4 && measured((bit1(0x0E05B6) +
                 bit2(0x0E05B6) + bit3(0x0E05B6) + bit4(0x0E05B6) + bit7(0x0E05B6)) == 5, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 6 && ParcoursCouranteFr() == 1 && (prev(bit1(0x0E06EE)) + prev(bit2(0x0E06EE)) +
                 prev(bit3(0x0E06EE)) + prev(bit4(0x0E06EE)) + prev(bit7(0x0E06EE))) == 4 && measured((bit1(0x0E06EE) +
                 bit2(0x0E06EE) + bit3(0x0E06EE) + bit4(0x0E06EE) + bit7(0x0E06EE)) == 5, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 6 && PistaActualEs() == 1 && (prev(bit1(0x0E0756)) + prev(bit2(0x0E0756)) +
                 prev(bit3(0x0E0756)) + prev(bit4(0x0E0756)) + prev(bit7(0x0E0756))) == 4 && measured((bit1(0x0E0756) +
                 bit2(0x0E0756) + bit3(0x0E0756) + bit4(0x0E0756) + bit7(0x0E0756)) == 5, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Fraggle Rock", points = 10,
    description = "Complete all the objectives in Fraggle Rock",
    id = 129029, badge = "142001", published = "2020-10-13 4:34:28 PM", modified = "2022-07-27 9:15:11 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 6 && CurrentCourseUs() == 2 && (prev(FraggleRockObjectiveFlagsUs()) + prev(FraggleRockObjectiveFlagsUs()) +
                 prev(FraggleRockObjectiveFlagsUs()) + prev(FraggleRockObjectiveFlagsUs()) + prev(FraggleRockObjectiveFlagsUs())) == 4 && measured((FraggleRockObjectiveFlagsUs() +
                 FraggleRockObjectiveFlagsUs() + FraggleRockObjectiveFlagsUs() + FraggleRockObjectiveFlagsUs() + FraggleRockObjectiveFlagsUs()) == 5, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 6 && CurrentCourseEu() == 2 && (prev(bit1(0x0E1E56)) + prev(bit2(0x0E1E56)) +
                 prev(bit3(0x0E1E56)) + prev(bit4(0x0E1E56)) + prev(bit7(0x0E1E56))) == 4 && measured((bit1(0x0E1E56) +
                 bit2(0x0E1E56) + bit3(0x0E1E56) + bit4(0x0E1E56) + bit7(0x0E1E56)) == 5, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 6 && AktuelleStreckeDe() == 2 && (prev(bit1(0x0E05AE)) + prev(bit2(0x0E05AE)) +
                 prev(bit3(0x0E05AE)) + prev(bit4(0x0E05AE)) + prev(bit7(0x0E05AE))) == 4 && measured((bit1(0x0E05AE) +
                 bit2(0x0E05AE) + bit3(0x0E05AE) + bit4(0x0E05AE) + bit7(0x0E05AE)) == 5, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 6 && PercorsoCorrenteIt() == 2 && (prev(bit1(0x0E05BE)) + prev(bit2(0x0E05BE)) +
                 prev(bit3(0x0E05BE)) + prev(bit4(0x0E05BE)) + prev(bit7(0x0E05BE))) == 4 && measured((bit1(0x0E05BE) +
                 bit2(0x0E05BE) + bit3(0x0E05BE) + bit4(0x0E05BE) + bit7(0x0E05BE)) == 5, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 6 && ParcoursCouranteFr() == 2 && (prev(bit1(0x0E06F6)) + prev(bit2(0x0E06F6)) +
                 prev(bit3(0x0E06F6)) + prev(bit4(0x0E06F6)) + prev(bit7(0x0E06F6))) == 4 && measured((bit1(0x0E06F6) +
                 bit2(0x0E06F6) + bit3(0x0E06F6) + bit4(0x0E06F6) + bit7(0x0E06F6)) == 5, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 6 && PistaActualEs() == 2 && (prev(bit1(0x0E075E)) + prev(bit2(0x0E075E)) +
                 prev(bit3(0x0E075E)) + prev(bit4(0x0E075E)) + prev(bit7(0x0E075E))) == 4 && measured((bit1(0x0E075E) +
                 bit2(0x0E075E) + bit3(0x0E075E) + bit4(0x0E075E) + bit7(0x0E075E)) == 5, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "100% Disco", points = 10,
    description = "Complete all the objectives in Disco",
    id = 129030, badge = "142002", published = "2020-10-13 4:34:32 PM", modified = "2022-07-27 9:15:23 AM",
    trigger = always_true() &&
              ((CurrentCourseSetUs() == 6 && CurrentCourseUs() == 3 && (prev(DiscoObjectiveFlagsUs()) + prev(DiscoObjectiveFlagsUs()) +
                 prev(DiscoObjectiveFlagsUs()) + prev(DiscoObjectiveFlagsUs()) + prev(DiscoObjectiveFlagsUs())) == 4 && measured((DiscoObjectiveFlagsUs() +
                 DiscoObjectiveFlagsUs() + DiscoObjectiveFlagsUs() + DiscoObjectiveFlagsUs() + DiscoObjectiveFlagsUs()) == 5, when=MusicVolumeUs() <= 15 &&
                 SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6 && (CurrentCourseSetUs() == 255 ||
                 CurrentCourseSetUs() <= 8) && (CurrentCourseUs() == 255 || CurrentCourseUs() <= 3) && SwampBestLapCharacterUs() <= 24 &&
                 SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1)) ||
               (CurrentCourseSetEu() == 6 && CurrentCourseEu() == 3 && (prev(bit1(0x0E1E5E)) + prev(bit2(0x0E1E5E)) +
                 prev(bit3(0x0E1E5E)) + prev(bit4(0x0E1E5E)) + prev(bit7(0x0E1E5E))) == 4 && measured((bit1(0x0E1E5E) +
                 bit2(0x0E1E5E) + bit3(0x0E1E5E) + bit4(0x0E1E5E) + bit7(0x0E1E5E)) == 5, when=MusicVolumeEu() <= 15 &&
                 SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6 && (CurrentCourseSetEu() == 255 ||
                 CurrentCourseSetEu() <= 8) && (CurrentCourseEu() == 255 || CurrentCourseEu() <= 3) && byte(0x0E1D84) <= 24 &&
                 byte(0x0E1D85) <= 30 && SwampObjectiveFlagsEu() == 1 && byte(0x0E1D87) == 1)) ||
               (AktuelleSetVonStreckenDe() == 6 && AktuelleStreckeDe() == 3 && (prev(bit1(0x0E05B6)) + prev(bit2(0x0E05B6)) +
                 prev(bit3(0x0E05B6)) + prev(bit4(0x0E05B6)) + prev(bit7(0x0E05B6))) == 4 && measured((bit1(0x0E05B6) +
                 bit2(0x0E05B6) + bit3(0x0E05B6) + bit4(0x0E05B6) + bit7(0x0E05B6)) == 5, when=MusiklautstärkeDe() <= 15 &&
                 TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6 && byte(0x0E04DC) <= 24 &&
                 byte(0x0E04DD) <= 30 && FlagsVonZieleVonSumpfDe() == 1 && byte(0x0E04DF) == 1)) ||
               (SetDiPercorsiCorrenteIt() == 6 && PercorsoCorrenteIt() == 3 && (prev(bit1(0x0E05C6)) + prev(bit2(0x0E05C6)) +
                 prev(bit3(0x0E05C6)) + prev(bit4(0x0E05C6)) + prev(bit7(0x0E05C6))) == 4 && measured((bit1(0x0E05C6) +
                 bit2(0x0E05C6) + bit3(0x0E05C6) + bit4(0x0E05C6) + bit7(0x0E05C6)) == 5, when=VolumeDellaMusicaIt() <= 15 &&
                 VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6 && byte(0x0E04EC) <= 24 &&
                 byte(0x0E04ED) <= 30 && bit0(0x0E04EE) == 1 && byte(0x0E04EF) == 1)) ||
               (SetDeParcoursesCouranteFr() == 6 && ParcoursCouranteFr() == 3 && (prev(bit1(0x0E06FE)) + prev(bit2(0x0E06FE)) +
                 prev(bit3(0x0E06FE)) + prev(bit4(0x0E06FE)) + prev(bit7(0x0E06FE))) == 4 && measured((bit1(0x0E06FE) +
                 bit2(0x0E06FE) + bit3(0x0E06FE) + bit4(0x0E06FE) + bit7(0x0E06FE)) == 5, when=byte(0x0BA010) <= 15 &&
                 byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6 && byte(0x0E0624) <= 24 &&
                 byte(0x0E0625) <= 30 && FlagsDObjectifsDeMaraisFr() == 1 && byte(0x0E0627) == 1)) ||
               (SetDePistasActualEs() == 6 && PistaActualEs() == 3 && (prev(bit1(0x0E0766)) + prev(bit2(0x0E0766)) +
                 prev(bit3(0x0E0766)) + prev(bit4(0x0E0766)) + prev(bit7(0x0E0766))) == 4 && measured((bit1(0x0E0766) +
                 bit2(0x0E0766) + bit3(0x0E0766) + bit4(0x0E0766) + bit7(0x0E0766)) == 5, when=VolumenDeMúsicaEs() <= 15 &&
                 VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6 && byte(0x0E068C) <= 24 &&
                 byte(0x0E068D) <= 30 && FlagsDeObjetivosDeCiénagaEs() == 1 && byte(0x0E068F) == 1)))
)

achievement(
    title = "Race A winner", points = 10,
    description = "Win the Race A tournament",
    id = 128999, badge = "141778", published = "2020-10-13 4:31:22 PM", modified = "2022-07-27 10:14:37 AM",
    trigger = always_true() &&
              ((InTournamentUs() == 1 && CurrentTournamentUs() == 0 && AddedCurrentlyCompletedRaceSPointsUs() == 2 && CurrentCourseUs() == 0 && 
                NumberOfRacesFinishedInTournamentUs() == 6 && PlayerSTournamentScoreUs() > Com1STournamentScoreUs() && PlayerSTournamentScoreUs() > Com2STournamentScoreUs() && 
                PlayerSTournamentScoreUs() > Com3STournamentScoreUs() && PlayerSTournamentScoreUs() > Com4STournamentScoreUs() && PlayerSTournamentScoreUs() > Com5STournamentScoreUs() && 
                MusicVolumeUs() <= 15 && SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6) ||
               (InTournamentEu() == 1 && byte(0x0C26F8) == 0 && AddedCurrentlyCompletedRaceSPointsEu() == 2 && CurrentCourseEu() == 1 && 
                NumberOfRacesFinishedInTournamentEu() == 6 && PlayerSTournamentScoreEu() > Com1STournamentScoreEu() && PlayerSTournamentScoreEu() > Com2STournamentScoreEu() && 
                PlayerSTournamentScoreEu() > Com3STournamentScoreEu() && PlayerSTournamentScoreEu() > Com4STournamentScoreEu() && PlayerSTournamentScoreEu() > Com5STournamentScoreEu() && 
                MusicVolumeEu() <= 15 && SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6) ||
               (ImTurnierDe() == 1 && byte(0x0C1920) == 0 && PunkteDesTurniersSummiertDe() == 2 && AktuelleStreckeDe() == 0 && 
                NummerVonFertigeRennenImTurnierDe() == 6 && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom1ImTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom2InTurnierDe() && 
                PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom3InmTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom4ImTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom5ImTurnierDe() && 
                MusiklautstärkeDe() <= 15 && TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6) ||
               (NellTorneoIt() == 1 && byte(0x0C1930) == 0 && PuntiDelTorneoAggiuntiIt() == 2 && PercorsoCorrenteIt() == 0 && 
                NumeroDiGareFiniteNelTorneoIt() == 6 && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom1NelTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom2NelTorneoIt() && 
                PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom3NellTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom4NellTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom5NellTorneoIt() && 
                VolumeDellaMusicaIt() <= 15 && VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6) ||
               (DansLeTournoiFr() == 1 && byte(0x0C1A68) == 0 && PointsDuTournoiAjoutésFr() == 2 && ParcoursCouranteFr() == 0 && 
                NombreDeCoursesFinisDansLeTournoiFr() == 6 && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom1DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom2DansLeTournoiFr() && 
                PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom3DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom4DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom5DansLeTournoiFr() && 
                byte(0x0BA010) <= 15 && byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6) ||
               (EnTorneoEs() == 1 && byte(0x0C1AD0) == 0 && PuntosDeTorneoSumadosEs() == 2 && PistaActualEs() == 0 && 
                NúmeroDeCarrerasAcabadasEnTorneoEs() == 6 && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom1EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom2EnTorneoEs() && 
                PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom3EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom4EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom5EnTorneoEs() && 
                VolumenDeMúsicaEs() <= 15 && VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6))
)

achievement(
    title = "Race A champion", points = 25,
    description = "Get 30 points in the Race A tournament",
    id = 129000, badge = "141779", published = "2020-10-13 4:31:27 PM", modified = "2022-07-27 10:15:14 AM",
    trigger = always_true() &&
              ((InTournamentUs() == 1 && CurrentTournamentUs() == 0 && AddedCurrentlyCompletedRaceSPointsUs() == 2 && CurrentCourseUs() == 0 && 
                NumberOfRacesFinishedInTournamentUs() == 6 && PlayerSTournamentScoreUs() > Com1STournamentScoreUs() && PlayerSTournamentScoreUs() > Com2STournamentScoreUs() && 
                PlayerSTournamentScoreUs() > Com3STournamentScoreUs() && PlayerSTournamentScoreUs() > Com4STournamentScoreUs() && PlayerSTournamentScoreUs() > Com5STournamentScoreUs() && 
                PlayerSTournamentScoreUs() >= 30 && MusicVolumeUs() <= 15 && SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && 
                PlayerSRacePositionUs() <= 6) ||
               (InTournamentEu() == 1 && byte(0x0C26F8) == 0 && AddedCurrentlyCompletedRaceSPointsEu() == 2 && CurrentCourseEu() == 0 && 
                NumberOfRacesFinishedInTournamentEu() == 6 && PlayerSTournamentScoreEu() > Com1STournamentScoreEu() && PlayerSTournamentScoreEu() > Com2STournamentScoreEu() && 
                PlayerSTournamentScoreEu() > Com3STournamentScoreEu() && PlayerSTournamentScoreEu() > Com4STournamentScoreEu() && PlayerSTournamentScoreEu() > Com5STournamentScoreEu() && 
                PlayerSTournamentScoreEu() >= 30 && MusicVolumeEu() <= 15 && SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && 
                PlayerSRacePositionEu() <= 6) ||
               (ImTurnierDe() == 1 && byte(0x0C1920) == 0 && PunkteDesTurniersSummiertDe() == 2 && AktuelleStreckeDe() == 0 && 
                NummerVonFertigeRennenImTurnierDe() == 6 && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom1ImTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom2InTurnierDe() && 
                PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom3InmTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom4ImTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom5ImTurnierDe() && 
                PunktzahlDesSpielersImTurnierDe() >= 30 && MusiklautstärkeDe() <= 15 && TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && 
                PlatzImRennenDe() <= 6) ||
               (NellTorneoIt() == 1 && byte(0x0C1930) == 0 && PuntiDelTorneoAggiuntiIt() == 2 && PercorsoCorrenteIt() == 0 && 
                NumeroDiGareFiniteNelTorneoIt() == 6 && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom1NelTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom2NelTorneoIt() && 
                PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom3NellTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom4NellTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom5NellTorneoIt() && 
                PunteggioDelGiocatoreNelTorneoIt() >= 30 && VolumeDellaMusicaIt() <= 15 && VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && 
                PosizioneDelGiocatoreIt() <= 6) ||
               (DansLeTournoiFr() == 1 && byte(0x0C1A68) == 0 && PointsDuTournoiAjoutésFr() == 2 && ParcoursCouranteFr() == 0 && 
                NombreDeCoursesFinisDansLeTournoiFr() == 6 && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom1DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom2DansLeTournoiFr() && 
                PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom3DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom4DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom5DansLeTournoiFr() && 
                PonctuationDuJoueurDansLeTournoiFr() >= 30 && byte(0x0BA010) <= 15 && byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && 
                PositionDuJoueurFr() <= 6) ||
               (EnTorneoEs() == 1 && byte(0x0C1AD0) == 0 && PuntosDeTorneoSumadosEs() == 2 && PistaActualEs() == 0 && 
                NúmeroDeCarrerasAcabadasEnTorneoEs() == 6 && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom1EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom2EnTorneoEs() && 
                PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom3EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom4EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom5EnTorneoEs() && 
                PuntuaciónDelJugadorEnTorneoEs() >= 30 && VolumenDeMúsicaEs() <= 15 && VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && 
                PosiciónDelJugadorEs() <= 6))
)

achievement(
    title = "Race B winner", points = 10,
    description = "Win the Race B tournament",
    id = 128997, badge = "141776", published = "2020-10-13 4:31:07 PM", modified = "2022-07-27 10:15:39 AM",
    trigger = always_true() &&
              ((InTournamentUs() == 1 && CurrentTournamentUs() == 1 && AddedCurrentlyCompletedRaceSPointsUs() == 2 && CurrentCourseUs() == 1 && 
                NumberOfRacesFinishedInTournamentUs() == 6 && PlayerSTournamentScoreUs() > Com1STournamentScoreUs() && PlayerSTournamentScoreUs() > Com2STournamentScoreUs() && 
                PlayerSTournamentScoreUs() > Com3STournamentScoreUs() && PlayerSTournamentScoreUs() > Com4STournamentScoreUs() && PlayerSTournamentScoreUs() > Com5STournamentScoreUs() && 
                MusicVolumeUs() <= 15 && SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && PlayerSRacePositionUs() <= 6) ||
               (InTournamentEu() == 1 && byte(0x0C1AD0) == 1 && byte(0x0C26F8) == 1 && AddedCurrentlyCompletedRaceSPointsEu() == 2 && 
                CurrentCourseEu() == 1 && NumberOfRacesFinishedInTournamentEu() == 6 && PlayerSTournamentScoreEu() > Com1STournamentScoreEu() && PlayerSTournamentScoreEu() >
                 Com2STournamentScoreEu() && PlayerSTournamentScoreEu() > Com3STournamentScoreEu() && PlayerSTournamentScoreEu() > Com4STournamentScoreEu() && PlayerSTournamentScoreEu()
                 > Com5STournamentScoreEu() && MusicVolumeEu() <= 15 && SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && 
                PlayerSRacePositionEu() <= 6) ||
               (ImTurnierDe() == 1 && byte(0x0C1920) == 1 && PunkteDesTurniersSummiertDe() == 2 && AktuelleStreckeDe() == 1 && 
                NummerVonFertigeRennenImTurnierDe() == 6 && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom1ImTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom2InTurnierDe() && 
                PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom3InmTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom4ImTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom5ImTurnierDe() && 
                MusiklautstärkeDe() <= 15 && TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && PlatzImRennenDe() <= 6) ||
               (NellTorneoIt() == 1 && byte(0x0C1930) == 1 && PuntiDelTorneoAggiuntiIt() == 2 && PercorsoCorrenteIt() == 1 && 
                NumeroDiGareFiniteNelTorneoIt() == 6 && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom1NelTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom2NelTorneoIt() && 
                PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom3NellTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom4NellTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom5NellTorneoIt() && 
                VolumeDellaMusicaIt() <= 15 && VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && PosizioneDelGiocatoreIt() <= 6) ||
               (DansLeTournoiFr() == 1 && byte(0x0C1A68) == 1 && PointsDuTournoiAjoutésFr() == 2 && ParcoursCouranteFr() == 1 && 
                NombreDeCoursesFinisDansLeTournoiFr() == 6 && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom1DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom2DansLeTournoiFr() && 
                PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom3DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom4DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom5DansLeTournoiFr() && 
                byte(0x0BA010) <= 15 && byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && PositionDuJoueurFr() <= 6) ||
               (EnTorneoEs() == 1 && PuntosDeTorneoSumadosEs() == 2 && PistaActualEs() == 1 && NúmeroDeCarrerasAcabadasEnTorneoEs() == 6 && 
                PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom1EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom2EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom3EnTorneoEs() && 
                PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom4EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom5EnTorneoEs() && VolumenDeMúsicaEs() <= 15 && 
                VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6))
)

achievement(
    title = "Race B champion", points = 25,
    description = "Get 30 points in the Race B tournament",
    id = 128998, badge = "141777", published = "2020-10-13 4:31:10 PM", modified = "2022-08-04 9:39:10 AM",
    trigger = always_true() &&
              ((InTournamentUs() == 1 && CurrentTournamentUs() == 1 && AddedCurrentlyCompletedRaceSPointsUs() == 2 && CurrentCourseUs() == 1 && 
                NumberOfRacesFinishedInTournamentUs() == 6 && PlayerSTournamentScoreUs() > Com1STournamentScoreUs() && PlayerSTournamentScoreUs() > Com2STournamentScoreUs() && 
                PlayerSTournamentScoreUs() > Com3STournamentScoreUs() && PlayerSTournamentScoreUs() > Com4STournamentScoreUs() && PlayerSTournamentScoreUs() > Com5STournamentScoreUs() && 
                PlayerSTournamentScoreUs() >= 30 && MusicVolumeUs() <= 15 && SoundVolumeUs() <= 15 && PlayerSBoostMax() <= 420 && 
                PlayerSRacePositionUs() <= 6) ||
               (InTournamentEu() == 1 && byte(0x0C26F8) == 1 && AddedCurrentlyCompletedRaceSPointsEu() == 2 && CurrentCourseEu() == 1 && 
                NumberOfRacesFinishedInTournamentEu() == 6 && PlayerSTournamentScoreEu() > Com1STournamentScoreEu() && PlayerSTournamentScoreEu() > Com2STournamentScoreEu() && 
                PlayerSTournamentScoreEu() > Com3STournamentScoreEu() && PlayerSTournamentScoreEu() > Com4STournamentScoreEu() && PlayerSTournamentScoreEu() > Com5STournamentScoreEu() && 
                PlayerSTournamentScoreEu() >= 30 && MusicVolumeEu() <= 15 && SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && 
                PlayerSRacePositionEu() <= 6) ||
               (ImTurnierDe() == 1 && byte(0x0C1920) == 1 && PunkteDesTurniersSummiertDe() == 2 && AktuelleStreckeDe() == 1 && 
                NummerVonFertigeRennenImTurnierDe() == 6 && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom1ImTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom2InTurnierDe() && 
                PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom3InmTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom4ImTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom5ImTurnierDe() && 
                PunktzahlDesSpielersImTurnierDe() >= 30 && MusiklautstärkeDe() <= 15 && TonlautstärkeDe() <= 15 && BoostDesSpielersDe() <= 420 && 
                PlatzImRennenDe() <= 6) ||
               (NellTorneoIt() == 1 && byte(0x0C1930) == 1 && PuntiDelTorneoAggiuntiIt() == 2 && PercorsoCorrenteIt() == 1 && 
                NumeroDiGareFiniteNelTorneoIt() == 6 && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom1NelTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom2NelTorneoIt() && 
                PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom3NellTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom4NellTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom5NellTorneoIt() && 
                PunteggioDelGiocatoreNelTorneoIt() >= 30 && VolumeDellaMusicaIt() <= 15 && VolumeDelSuonoIt() <= 15 && TurboDelGiocatoreIt() <= 420 && 
                PosizioneDelGiocatoreIt() <= 6) ||
               (DansLeTournoiFr() == 1 && byte(0x0C1A68) == 1 && PointsDuTournoiAjoutésFr() == 2 && ParcoursCouranteFr() == 1 && 
                NombreDeCoursesFinisDansLeTournoiFr() == 6 && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom1DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom2DansLeTournoiFr() && 
                PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom3DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom4DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom5DansLeTournoiFr() && 
                PonctuationDuJoueurDansLeTournoiFr() >= 30 && byte(0x0BA010) <= 15 && byte(0x0BA011) <= 15 && TurboDuJoueurFr() <= 420 && 
                PositionDuJoueurFr() <= 6) ||
               (EnTorneoEs() == 1 && PuntosDeTorneoSumadosEs() == 2 && PistaActualEs() == 1 && NúmeroDeCarrerasAcabadasEnTorneoEs() == 6 && 
                PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom1EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom2EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom3EnTorneoEs() && 
                PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom4EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom5EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() >= 30 && 
                VolumenDeMúsicaEs() <= 15 && VolumenDeSonidoEs() <= 15 && TurboDelJugadorEs() <= 420 && PosiciónDelJugadorEs() <= 6))
)

achievement(
    title = "Battle winner", points = 10,
    description = "Win the Battle tournament",
    id = 129001, badge = "141780", published = "2020-10-13 4:31:32 PM", modified = "2022-07-27 10:16:10 AM",
    trigger = always_true() &&
              ((InTournamentUs() == 1 && CurrentTournamentUs() == 2 && AddedCurrentlyCompletedRaceSPointsUs() == 2 && CurrentCourseUs() == 2 && 
                NumberOfRacesFinishedInTournamentUs() == 6 && PlayerSTournamentScoreUs() > Com1STournamentScoreUs() && PlayerSTournamentScoreUs() > Com2STournamentScoreUs() && 
                PlayerSTournamentScoreUs() > Com3STournamentScoreUs() && PlayerSTournamentScoreUs() > Com4STournamentScoreUs() && PlayerSTournamentScoreUs() > Com5STournamentScoreUs() && 
                MusicVolumeUs() <= 15 && SoundVolumeUs() <= 15 && PlayerSRacePositionUs() <= 6 && CurrentCourseSetUs() <= 8 && 
                SwampBestLapCharacterUs() <= 24 && SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && SwampObjectiveFlagsUs() == 1) ||
               (InTournamentEu() == 1 && byte(0x0C26F8) == 2 && AddedCurrentlyCompletedRaceSPointsEu() == 2 && CurrentCourseEu() == 2 && 
                NumberOfRacesFinishedInTournamentEu() == 6 && PlayerSTournamentScoreEu() > Com1STournamentScoreEu() && PlayerSTournamentScoreEu() > Com2STournamentScoreEu() && 
                PlayerSTournamentScoreEu() > Com3STournamentScoreEu() && PlayerSTournamentScoreEu() > Com4STournamentScoreEu() && PlayerSTournamentScoreEu() > Com5STournamentScoreEu() && 
                MusicVolumeEu() <= 15 && SoundVolumeEu() <= 15 && CurrentBoostEu() <= 420 && PlayerSRacePositionEu() <= 6) ||
               (ImTurnierDe() == 1 && byte(0x0C1920) == 2 && PunkteDesTurniersSummiertDe() == 2 && AktuelleStreckeDe() == 2 && 
                NummerVonFertigeRennenImTurnierDe() == 6 && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom1ImTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom2InTurnierDe() && 
                PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom3InmTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom4ImTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom5ImTurnierDe() && 
                MusiklautstärkeDe() <= 15 && TonlautstärkeDe() <= 15 && PlatzImRennenDe() <= 6) ||
               (NellTorneoIt() == 1 && byte(0x0C1930) == 2 && PuntiDelTorneoAggiuntiIt() == 2 && PercorsoCorrenteIt() == 2 && 
                NumeroDiGareFiniteNelTorneoIt() == 6 && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom1NelTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom2NelTorneoIt() && 
                PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom3NellTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom4NellTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom5NellTorneoIt() && 
                VolumeDellaMusicaIt() <= 15 && VolumeDelSuonoIt() <= 15 && PosizioneDelGiocatoreIt() <= 6) ||
               (DansLeTournoiFr() == 1 && byte(0x0C1A68) == 2 && PointsDuTournoiAjoutésFr() == 2 && ParcoursCouranteFr() == 2 && 
                NombreDeCoursesFinisDansLeTournoiFr() == 6 && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom1DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom2DansLeTournoiFr() && 
                PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom3DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom4DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom5DansLeTournoiFr() && 
                byte(0x0BA010) <= 15 && byte(0x0BA011) <= 15 && PositionDuJoueurFr() <= 6) ||
               (EnTorneoEs() == 1 && byte(0x0C1AD0) == 2 && PuntosDeTorneoSumadosEs() == 2 && PistaActualEs() == 2 && 
                NúmeroDeCarrerasAcabadasEnTorneoEs() == 6 && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom1EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom2EnTorneoEs() && 
                PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom3EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom4EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom5EnTorneoEs() && 
                VolumenDeMúsicaEs() <= 15 && VolumenDeSonidoEs() <= 15 && PosiciónDelJugadorEs() <= 6))
)

achievement(
    title = "Battle champion", points = 25,
    description = "Get 20 points in the Battle tournament",
    id = 129002, badge = "141781", published = "2020-10-13 4:31:36 PM", modified = "2022-07-27 10:16:34 AM",
    trigger = always_true() &&
              ((InTournamentUs() == 1 && CurrentTournamentUs() == 2 && AddedCurrentlyCompletedRaceSPointsUs() == 2 && CurrentCourseUs() == 2 && 
                NumberOfRacesFinishedInTournamentUs() == 6 && PlayerSTournamentScoreUs() > Com1STournamentScoreUs() && PlayerSTournamentScoreUs() > Com2STournamentScoreUs() && 
                PlayerSTournamentScoreUs() > Com3STournamentScoreUs() && PlayerSTournamentScoreUs() > Com4STournamentScoreUs() && PlayerSTournamentScoreUs() > Com5STournamentScoreUs() && 
                PlayerSTournamentScoreUs() >= 20 && MusicVolumeUs() <= 15 && SoundVolumeUs() <= 15 && PlayerSRacePositionUs() <= 6 && 
                CurrentCourseSetUs() <= 8 && SwampBestLapCharacterUs() <= 24 && SwampBestLapVehicleUs() <= 30 && bit0(0x0E0196) == 1 && 
                SwampObjectiveFlagsUs() == 1) ||
               (InTournamentEu() == 1 && byte(0x0C26F8) == 2 && AddedCurrentlyCompletedRaceSPointsEu() == 2 && CurrentCourseEu() == 2 && 
                NumberOfRacesFinishedInTournamentEu() == 6 && PlayerSTournamentScoreEu() > Com1STournamentScoreEu() && PlayerSTournamentScoreEu() > Com2STournamentScoreEu() && 
                PlayerSTournamentScoreEu() > Com3STournamentScoreEu() && PlayerSTournamentScoreEu() > Com4STournamentScoreEu() && PlayerSTournamentScoreEu() > Com5STournamentScoreEu() && 
                PlayerSTournamentScoreEu() >= 20 && MusicVolumeEu() <= 15 && SoundVolumeEu() <= 15 && PlayerSRacePositionEu() <= 6) ||
               (ImTurnierDe() == 1 && byte(0x0C1920) == 2 && PunkteDesTurniersSummiertDe() == 2 && AktuelleStreckeDe() == 2 && 
                NummerVonFertigeRennenImTurnierDe() == 6 && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom1ImTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom2InTurnierDe() && 
                PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom3InmTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom4ImTurnierDe() && PunktzahlDesSpielersImTurnierDe() > PunktzahlVonCom5ImTurnierDe() && 
                PunktzahlDesSpielersImTurnierDe() >= 20 && MusiklautstärkeDe() <= 15 && TonlautstärkeDe() <= 15 && PlatzImRennenDe() <= 6) ||
               (NellTorneoIt() == 1 && byte(0x0C1930) == 2 && PuntiDelTorneoAggiuntiIt() == 2 && PercorsoCorrenteIt() == 2 && 
                NumeroDiGareFiniteNelTorneoIt() == 6 && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom1NelTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom2NelTorneoIt() && 
                PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom3NellTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom4NellTorneoIt() && PunteggioDelGiocatoreNelTorneoIt() > PunteggioDelCom5NellTorneoIt() && 
                PunteggioDelGiocatoreNelTorneoIt() >= 20 && VolumeDellaMusicaIt() <= 15 && VolumeDelSuonoIt() <= 15 && PosizioneDelGiocatoreIt() <= 6) ||
               (DansLeTournoiFr() == 1 && byte(0x0C1A68) == 2 && PointsDuTournoiAjoutésFr() == 2 && ParcoursCouranteFr() == 2 && 
                NombreDeCoursesFinisDansLeTournoiFr() == 6 && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom1DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom2DansLeTournoiFr() && 
                PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom3DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom4DansLeTournoiFr() && PonctuationDuJoueurDansLeTournoiFr() > PonctuationDuCom5DansLeTournoiFr() && 
                PonctuationDuJoueurDansLeTournoiFr() >= 20 && byte(0x0BA010) <= 15 && byte(0x0BA011) <= 15 && PositionDuJoueurFr() <= 6) ||
               (EnTorneoEs() == 1 && byte(0x0C1AD0) == 2 && PuntosDeTorneoSumadosEs() == 2 && PistaActualEs() == 2 && 
                NúmeroDeCarrerasAcabadasEnTorneoEs() == 6 && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom1EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom2EnTorneoEs() && 
                PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom3EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom4EnTorneoEs() && PuntuaciónDelJugadorEnTorneoEs() > PuntuaciónDeCom5EnTorneoEs() && 
                PuntuaciónDelJugadorEnTorneoEs() >= 20 && VolumenDeMúsicaEs() <= 15 && VolumenDeSonidoEs() <= 15 && PosiciónDelJugadorEs() <= 6))
)
